<?php
/**
 * Created by PhpStorm.
 * Project: kaizer
 * User: lxShaDoWxl
 * Date: 20.07.16
 * Time: 10:29
 */
namespace backend\controllers;

use backend\AdminController;
use backend\models\main\TextModel;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;

class TextController extends AdminController
{
    public function init()
    {
        $this->model = new TextModel();
        $this->url = [
            'back' => ['text/control'],
            'control' => ['text/control']
        ];
        $this->view->title = 'Текста';
        $this->MenuActive('text');
        $this->breadcrumb[] = [
            'url' => ['text/control'],
            'label' => 'Текста'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
//                    'filter' => ['post', 'get'],
                ],
            ],
        ];
    }
}