<?php
namespace backend\controllers;

use backend\AdminController;
use backend\models\EditUser;
use common\models\User;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;

class UsersController extends AdminController
{
    public function init()
    {
        $this->model = new EditUser();
        $controller_name = Inflector::camel2id($this->id);
        $this->url = [
            'back' => [$controller_name.'/index'],
            'control' => [$controller_name.'/control']
        ];
        $this->view->title = 'Пользователи сайта';
        $this->MenuActive($controller_name);
        $this->breadcrumb[] = [
            'url' => [$controller_name.'/index'],
            'label' => $this->view->title
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['admin'],
                    ],
                    [
                        'actions' => ['deleted'],
                        'allow' => false,
                        'roles' => ['loginAdminPanel'],
                    ],
                    [
                        'allow' => true,
                        'roles' => ['manager'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
                ],
            ],
        ];
    }
    public $current_type = 'all';
    public $data_types = [
        'all' => [
            'title' => 'Все'
        ],
        'no_wholesale' => [
            'title' => 'Розничные'
        ],
        'is_wholesale' => [
            'title' => 'Оптовые'
        ],
        'is_discount' => [
            'title' => 'Со скидкой'
        ],
    ];
    public function actionIndex()
    {
        $model = User::find()->orderBy(['id' => SORT_DESC])->with([
            'lastUserOrder'
        ]);
        if($sort=\Yii::$app->request->get('sort')){
            $this->current_type = $sort;
            switch($sort){
                case 'no_wholesale':
                    $model->andWhere(['isWholesale' => 0]);
                    break;
                case 'is_wholesale':
                    $model->andWhere(['isWholesale' => 1]);
                    break;
                case 'is_discount':
                    $model->andWhere('discount is NOT NULL');
                    break;
                default;
            }
        }
        $manager = \Yii::$app->request->get('manager',null);
//        if(\Yii::$app->user->identity->role=='manager'&&$manager!=null){
//            $manager = \Yii::$app->user->id;
//        }
        if($search=\Yii::$app->request->get('search')){
            $phone = preg_replace('/[^+\d]+/','',$search);

            if(  preg_match( '/^\+\d(\d{0,3})(\d{0,3})(\d{0,4})$/', $phone,  $matches ) )
            {
                $phone = '+7('.$matches[1];
                if($matches[2]){
                    $phone.=')-' .$matches[2];

                }
                if($matches[3]){
                    $phone.='-' . $matches[3];
                }
            }else{
                $phone = $search;
            }
            $model->andWhere([
                'or',
                ['like', 'username', $search],
                ['like', 'email', $search],
                ['like', 'phone', $phone],
            ]);
        }
        if($manager){
            $model->andWhere(['manager_id' => $manager]);
        }
        if($city=\Yii::$app->request->get('city')){
            $model->andWhere(['city_id' => $city]);
        }
        $data['search'] = $search;
        $data['select_city'] = $city;
        if(\Yii::$app->request->get('export')){
            User::export($model->all());
            \Yii::$app->end();
        }else{
            $pages = new Pagination(['totalCount' => $model->count()]);
            $size = \Yii::$app->request->get('size', 50);
            $pages->setPageSize($size);
            $data['size'] = $size;
            $data['pages'] = $pages;
            $data['items'] = $model->offset($pages->offset)
                ->limit($pages->limit)
                ->all();
            return $this->render('//main/users', $data);
        }
    }
    public function actionLogin($id)
    {
        $id_admin = \Yii::$app->user->id;
        \Yii::$app->user->logout();
        /**
         * @var $user User
         */
        $user = User::findOne($id);
        if ($user) {
            \Yii::$app->user->login($user, 0);
            \Yii::$app->session->set('return_admin_user', $id_admin);
        }
        return $this->goBack();
    }
    public function actionChangeField()
    {
        /**
         * @var $item User
         */
        $access_edit = [
            'isWholesale'
        ];
        if (($id = \Yii::$app->request->post('pk'))
            && ($name = \Yii::$app->request->post('name'))
            && in_array($name, $access_edit)
        ) {
            $value = \Yii::$app->request->post('value');
            \Yii::$app->db->createCommand()->update(
                User::tableName(),
                [
                    $name => $value
                ],
                [
                    'id' => $id
                ]
            )->execute();
        }
    }
}