<?php
namespace frontend\controllers;

use backend\modules\catalog\models\Category;
use backend\modules\catalog\models\DeliveryPrice;
use backend\modules\catalog\models\Items;
use backend\modules\catalog\models\Orders;
use backend\modules\catalog\models\OrdersPay;
use frontend\components\MainController;
use yii\caching\TagDependency;
use yii\web\BadRequestHttpException;
use yii\web\Response;

class ApiController extends MainController
{
    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
                'view' => '/site/error'
            ],
            'cart' => [
                'class' => 'frontend\components\CartAction',
            ],
        ];
    }
    public function actionIndexItems($action)
    {
        if (!\Yii::$app->request->isAjax) {
            throw new BadRequestHttpException();
        }
        if ($action == 'full') {
            $result = [
                'blocks' => Items::sliders_items()
            ];
        } elseif (
            $action == 'cat' &&
            ($block = \Yii::$app->request->get('block')) &&
            in_array($block, ['new', 'sale', 'hit']) &&
            ($id = \Yii::$app->request->get('id')) &&
            ($cat = Category::findOne($id))
        ) {
            $cats_items = $cat->getAllSubItemCats();
            $items = Items::list_items($block, 12, true)
                ->andWhere(['items.cid' => $cats_items])
                ->with([
                    'itemOptionsValues' => function ($q) {
                        /** @var \yii\db\ActiveQuery $q */
                        $q->with(['option', 'optionValue'])
                            ->join('LEFT JOIN', 'options_category', '`options_category`.`option_id` = `item_options_value`.`option_id`')
                            ->join('LEFT JOIN', 'options', '`options`.`id` = `item_options_value`.`option_id`')
                            ->andWhere(['OR', ['options_category.isList' => 1], ['options.isList' => 1]]);
                    }
                ])
                ->all();
            $result = [
                'items' => $this->renderPartial('//blocks/items_block', [
                    'items' => $items
                ])
            ];
        } else {
            throw new BadRequestHttpException();
        }
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return $result;
    }
    public function actionPriceDelivery($id,$weight)
    {
        if (!\Yii::$app->request->isAjax||!floatval($weight)) {
            throw new BadRequestHttpException();
        }
        \Yii::$app->response->format = Response::FORMAT_JSON;
        /** @var DeliveryPrice $item */
        $item = DeliveryPrice::find()->andWhere(['id' => $id])->one();
        if($item){
            $price = (float)$weight * $item->price_kg;
            return [
                'price_delivery' => \Yii::$app->formatter->asDecimal($price, 0) . ' <i class="tenge">b</i>',
                'time_delivery' =>$item->time.' дня',
            ];
        }else{
            throw new BadRequestHttpException();
        }
    }
    public function actionSuccessPay()
    {
        $headers      = \Yii::$app->request->getHeaders();
        $request_hmac = $headers->get('Content-HMAC');
        if (!$request_hmac) {
            \Yii::error('Not header Content-HMAC');
            exit;
        }
        $message = \Yii::$app->request->queryString;
        $s       = hash_hmac('sha256', $message, \Yii::$app->params['cloudpayments']['apiKey'], true);
        $hmac    = base64_encode($s);
        if ($request_hmac != $hmac) {
            \Yii::error('No validate header Content-HMAC');
            exit("hmac error");
        }
        $TransactionId = \Yii::$app->request->get('TransactionId');
        $Amount        = \Yii::$app->request->get('Amount');
        $InvoiceId     = \Yii::$app->request->get('InvoiceId');
        $order         = Orders::findOne($InvoiceId);
        if ($order) {
            \Yii::$app->db->createCommand()->insert(OrdersPay::tableName(), [
                'id'       => $TransactionId,
                'order_id' => $order->id,
                'amount'   => $Amount,
                'status'   => 0
            ])->execute();
            if ($order->pay_status == 'wait_surcharge') {
                Orders::updateAll(['pay_status' => 'success_surcharge'], ['id' => $order->id]);
            } else {
                Orders::updateAll(['pay_status' => 'success'], ['id' => $order->id]);
            }
        } else {
            \Yii::error('no correct InvoiceId');
            exit("no correct InvoiceId");
        }
        \Yii::$app->response->format = Response::FORMAT_JSON;
        return [
            'code' => 0
        ];
    }
	  

}