<?php
/**
 * Created by PhpStorm.
 * Project: morkovka
 * User: lxShaDoWxl
 * Date: 27.08.15
 * Time: 11:35
 */

namespace frontend\controllers;

use backend\modules\catalog\models\Orders;
use common\models\User;
use common\models\UserAddress;
use frontend\components\MainController;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\web\BadRequestHttpException;
use yii\web\Response;

class UserController extends MainController
{
    /**
     * Declares external actions for the controller.
     * This method is meant to be overwritten to declare external actions for the controller.
     * It should return an array, with array keys being action IDs, and array values the corresponding
     * action class names or action configuration arrays. For example,
     *
     * ~~~
     * return [
     *     'action1' => 'app\components\Action1',
     *     'action2' => [
     *         'class' => 'app\components\Action2',
     *         'property1' => 'value1',
     *         'property2' => 'value2',
     *     ],
     * ];
     * ~~~
     *
     * [[\Yii::createObject()]] will be used later to create the requested action
     * using the configuration provided here.
     */
    public function actions()
    {
        return [
            'send-form' => [
                'class' => 'frontend\components\SendFormAction',
                'forms' => [
                    'edit_profile'  => 'EditLk',
                    'address'       => 'EditAddress',
                    'edit_password' => 'EditPassword',
                    'replay-order'  => 'ReplayOrder',
                    'edit_subs'     => 'EditSubs',
                    'invited'       => 'InvitedSend',
                ]
            ],
        ];
    }
    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->breadcrumbs[] = [
            'label' => 'Мой кабинет',
            'url'   => ['user/index'],
        ];
    }

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
//                    'logout' => ['post'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $this->SeoSettings(false, false, 'Мой кабинет');
        return $this->render('index');
    }
    public function actionSettings()
    {
        $this->SeoSettings(false, false, 'Мои настройки');
        $this->breadcrumbs[] = [
            'label' => 'Мои настройки',
            'url'   => ['user/settings'],
        ];
        return $this->render('settings');
    }
    public function actionOrders()
    {
        $this->breadcrumbs[] = [
            'label' => 'Мои заказы',
            'url'   => ['user/orders'],
        ];
        if ($id = Yii::$app->request->get('id')) {
            if ($order = Orders::find()
                ->joinWith([
                    'ordersItems',
                ])
                ->andWhere('`orders_items`.id is NOT NULL')
                ->andWhere(['orders.id' => $id, 'user_id' => Yii::$app->user->id])
                ->with(['ordersItems.item'])
                ->one()) {
                $this->breadcrumbs[] = [
                    'label' => 'Заказ №' . $order->id,
                    'url'   => ['user/orders', 'id' => $id],
                ];
                $this->SeoSettings(false, false, 'Заказ №' . $order->id);
                return $this->render('order', ['order' => $order]);
            } else {
                return $this->redirect(['user/orders']);
            }
        } else {
            $this->SeoSettings(false, false, 'Мои заказы');
            return $this->render('orders');
        }
    }
    public function actionBonus()
    {
        $this->SeoSettings(false, false, 'Мои бонусы');
        /** @var User $user */
        $user =Yii::$app->user->identity;
        if (!$user->code) {
            $code = $user->generateCode();
            Yii::$app->db->createCommand()->update($user->tableName(), ['code' => $code], ['id' => $user->id])->execute();
        } else {
            $code = $user->code;
        }
        $this->breadcrumbs[] = [
            'label' => 'Мои бонусы',
            'url'   => ['user/orders'],
        ];
        return $this->render('bonus',['code'=>$code]);
    }
    public function actionAddress()
    {
        $this->SeoSettings(false, false, 'Мои адреса');
        $this->breadcrumbs[] = [
            'label' => 'Мои адреса',
            'url'   => ['user/address'],
        ];
        return $this->render('address');
    }

    public function actionAddAddress()
    {
        $this->SeoSettings(false, false, 'Добавление нового адреса');
        $this->breadcrumbs[] = [
            'label' => 'Мои адреса',
            'url'   => ['user/address'],
        ];
        $this->breadcrumbs[] = [
            'label' => 'Добавление нового адреса',
            'url'   => ['user/add-address'],
        ];
        return $this->render('add-address');
    }
    public function actionEditAddress($id)
    {
        $address = UserAddress::find()->andWhere(['user_id' => $this->user->id, 'id' => $id])->one();
        if ($address) {
            $this->SeoSettings(false, false, 'Добавление нового адреса');
            $this->breadcrumbs[] = [
                'label' => 'Мои адреса',
                'url'   => ['user/address'],
            ];
            $this->breadcrumbs[] = [
                'label' => 'Изменение адреса',
                'url'   => ['user/edit-address', 'id' => $id],
            ];
            return $this->render('add-address', ['address' => $address]);
        } else {
            throw new BadRequestHttpException('Данный адрес не найдён');
        }
    }
    public function actionReplayOrder()
    {
        if ($id = Yii::$app->request->get('id')) {
            /**@var $order Orders * */
            $order = Orders::find()
                ->joinWith([
//                    'ordersSets',
                    'ordersItems',
                ])
                ->andWhere('`orders_items`.id is NOT NULL')
                ->andWhere(['orders.id' => $id, 'user_id' => Yii::$app->user->id])
                ->with(['ordersItems.item'])
                ->one();
            if ($order) {
                $sets          = [];
                $items         = [];
                $type_handling = [];
                foreach ($order->ordersItems as $item_order) {
                    $items[$item_order->item_id] = $item_order->count;
//                    $type_handling[$item_order->item_id] = $item_order->getOrdersItemsHandings()->select('type_handling_id')->column();
                }
//                foreach ($order->ordersSets as $item_order) {
//                    $items[$item_order->set_id] = $item_order->count;
//                }
                if ($items) {
                    Yii::$app->session->set('items', $items);
                }
                if ($type_handling) {
                    Yii::$app->session->set('type_handling', $type_handling);
                }
                if ($sets) {
                    Yii::$app->session->set('sets', $sets);
                }
                return $this->redirect(['site/basket']);
            } else {
                return $this->redirect(['user/orders']);
            }
        } else {
            return $this->redirect(['user/orders']);
        }
    }
    public function actionWholesale()
    {
        if (Yii::$app->user->identity->isWholesale == 1) {
            $this->SeoSettings(false, false, 'Мои прайс-лист');
            return $this->render('wholesale');
        } else {
            throw new BadRequestHttpException('У вас нету доступа');
        }
    }
    public function actionPriceList($id)
    {
        if (Yii::$app->user->identity->isWholesale != 1) {
            throw new BadRequestHttpException('У вас нету доступа');
        } else {
            $items  = Items::find()->andWhere(['cid' => $id])->andWhere([
                'OR',
                ['isVisible' => 1],
                ['isVisible' => 0, 'isWholesale' => 1]
            ])->all();
            $result = [
                'items' => $this->renderPartial('items_price_list', ['items' => $items])
            ];
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                return $result;
            } else {
                return $this->render('wholesale_price', $result);
            }
        }
    }
}