<?php
/**
 * Created by PhpStorm.
 * Project: morkovka
 * User: lxShaDoWxl
 * Date: 03.09.15
 * Time: 11:11
 */
namespace backend\components\widgets;

use Yii;

class AuthChoice extends \yii\authclient\widgets\AuthChoice
{
    public $addClients;
    /**
     * Initializes the widget.
     */
    public function init()
    {
        if($this->addClients){
            foreach ($this->addClients as $clientId=>$config) {
                $config['id'] = $clientId;
//                $config = [
//                    'id' => $clientId,
//                    'class' => 'yii\authclient\clients\GoogleOAuth',
//                    'clientId' => '400286236239-rjbspkf2jiu86ag69grj1vfmkdmpht4c.apps.googleusercontent.com',
//                    'clientSecret' => 'w2H03oIZgzk1DGXl7b_D2EHq',
//                ];
                $clients[$clientId] = Yii::createObject($config);
            }
            $this->setClients($clients);
        }
        parent::init(); // TODO: Change the autogenerated stub
    }

}