<?php

namespace common\models;

use Yii;
use yii\helpers\Inflector;

/**
 * This is the model class for table "bonus_settings".
 *
 * @property integer $id
 * @property double  $percent
 * @property integer $price_start
 * @property integer $price_end
 */
class BonusSettings extends \shadow\SActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bonus_settings';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['percent'], 'required'],
            [['percent'], 'number'],
            [['price_start', 'price_end'], 'integer']
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'          => 'ID',
            'percent'     => 'Процент',
            'price_start' => 'Начальная сумма',
            'price_end'   => 'Конечная сумма',
        ];
    }
    public function FormParams()
    {
        $controller_name = Inflector::camel2id(Yii::$app->controller->id);
        $result          = [
            'form_action' => ["$controller_name/save"],
            'cancel'      => ["$controller_name/index"],
            'fields'      => [
                'percent'     => [],
                'price_start' => [],
                'price_end'   => [],
            ],
        ];
        return $result;
    }
    public function saveClear($event)
    {
        /**
         * @var $frontend_cache \yii\caching\FileCache
         */
        $frontend_cache = Yii::$app->frontend_cache;
        $frontend_cache->delete('bonus_settings');
        parent::saveClear($event); // TODO: Change the autogenerated stub
    }
    /**
     * @return array|mixed|BonusSettings[]
     */
    public static function all()
    {
        $all = Yii::$app->cache->get('bonus_settings');
        if (!$all) {
            $all = self::find()->orderBy(['price_start' => SORT_ASC])->all();
            Yii::$app->cache->set('bonus_settings', $all);
        }
        return $all;
    }
}
