<?php
/**
 * Created by PhpStorm.
 * Project: yii2-cms
 * User: viktor
 * Date: 20.04.15
 * Time: 15:52
 */

namespace shadow\widgets;


use shadow\assets\AdminActiveFormAsset;
use yii\bootstrap\ActiveForm;
use yii\helpers\Json;

class AdminActiveForm extends ActiveForm {
    /**
     * @var string the default field class name when calling [[field()]] to create a new field.
     * @see fieldConfig
     */
    public $fieldClass = 'shadow\widgets\AdminActiveField';
	public function run()
	{
		if ($this->enableClientScript) {
			$id = $this->options['id'];
			$options = Json::encode($this->getClientOptions());
			$attributes = Json::encode($this->attributes);
			$view = $this->getView();
			AdminActiveFormAsset::register($view);
			$view->registerJs("jQuery('#$id').yiiActiveForm($attributes, $options);");
			$this->enableClientScript = false;
		}
		parent::run(); // TODO: Change the autogenerated stub
	}
}