<?php
/**
 * Created by PhpStorm.
 * Project: morkovka
 * User: lxShaDoWxl
 * Date: 08.09.15
 * Time: 13:47
 */
namespace shadow\widgets;

use unclead\multipleinput\MultipleInput;
use yii\bootstrap\ActiveField;
use yii\helpers\Html;

class AdminActiveField extends ActiveField
{
    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->inputOptions['autocomplete'] = 'off';
    }
    public function imgInput($options = [])
    {
        // https://github.com/yiisoft/yii2/pull/795
        $deleted = false;
        if (isset($options['deleted'])) {
            $deleted = $options['deleted'];
            unset($options['deleted']);
        }
        if ($this->inputOptions !== ['class' => 'form-control']) {
            $options = array_merge($this->inputOptions, $options);
        }
        $this->adjustLabelFor($options);
        $input = Html::activeFileInput($this->model, $this->attribute, $options);
        if (isset($this->model->{$this->attribute}) && $this->model->{$this->attribute}) {
            $src = $this->model->{$this->attribute};
            $id = Html::getInputId($this->model, $this->attribute);
            if ($deleted) {
                $deleted_button = Html::a('<i class="fa fa-trash"></i>', '#', ['class' => 'btn btn-sm btn-danger deleted_img_input', 'data-input' => $id]);
                \Yii::$app->view->registerJs(<<<JS
$('.deleted_img_input').on('click',function(e) {
    e.preventDefault();
    var input = $('<input type="hidden" >');
    var input_orig = $('#'+$(this).data('input'));
    $(input).val('deleted');
    $(input).attr('name',$(input_orig).attr('name'));
    $(input_orig).after(input);
    $('#preview_'+$(this).data('input')).remove();
})
JS
,4,'deleted_img_input');
            } else {
                $deleted_button = '';
            }
            $img = Html::tag('div', Html::a($src, $src, ['target' => '_blank']).'<br />'.Html::a(Html::img($src, ['style' => 'max-height: 150px;']), $src, ['target' => '_blank']) . $deleted_button,['id'=>'preview_'.$id]);
        } else {
            $img = '';
        }
        $this->parts['{input}'] = $input . $img;
        return $this;
    }
    public function fileInput($options = [])
    {
        // https://github.com/yiisoft/yii2/pull/795
        if ($this->inputOptions !== ['class' => 'form-control']) {
            $options = array_merge($this->inputOptions, $options);
        }
        $deleted = false;
        if (isset($options['deleted'])) {
            $deleted = $options['deleted'];
            unset($options['deleted']);
        }
        $this->adjustLabelFor($options);
        $input = Html::activeFileInput($this->model, $this->attribute, $options);
        if (isset($this->model->{$this->attribute}) && $this->model->{$this->attribute}) {
            $src = $this->model->{$this->attribute};
            if ($deleted) {
                $id = Html::getInputId($this->model, $this->attribute);
                $deleted_button = Html::a('<i class="fa fa-trash"></i>', '#', ['class' => 'btn btn-sm btn-danger deleted_file_input', 'data-input' => $id]);
                \Yii::$app->view->registerJs(<<<JS
$('.deleted_file_input').on('click',function(e) {
    e.preventDefault();
    var input = $('<input type="hidden" >');
    var input_orig = $('#'+$(this).data('input'));
    $(input).val('deleted');
    $(input).attr('name',$(input_orig).attr('name'));
    $(input_orig).after(input);
    $('#preview_'+$(this).data('input')).remove();
})
JS
                    ,4,'deleted_file_input');
            } else {
                $deleted_button = '';
            }
            $file = Html::tag('div', Html::a($src, $src, ['target' => '_blank']).$deleted_button,['id'=>'preview_'.$id]);
        } else {
            $file = '';
        }
        $this->parts['{input}'] = $input . $file;
        return $this;
    }

    public function multipleInput($columns, $options = [], $max = 10, $attributeOptions = [])
    {
        if ($this->inputOptions !== ['class' => 'form-control']) {
            $options = array_merge($this->inputOptions, $options);
        }

        $this->adjustLabelFor($options);

        if (empty($attributeOptions)) {
            $attributeOptions = [
                'enableAjaxValidation'   => false,
                'enableClientValidation' => false,
                'validateOnChange'       => false,
                'validateOnSubmit'       => false,
                'validateOnBlur'         => false
            ];
        }

        if (empty($max)) {
            $max = 10;
        }

        $input = MultipleInput::widget([
            'model' => $this->model,
            'attribute' => $this->attribute,
            'attributeOptions' => $attributeOptions,
            'max' => $max,
            'columns' => $columns
        ]);

        $this->parts['{input}'] = $input;

        return $this;
    }
}