<?php
namespace frontend\form;

use backend\modules\catalog\models\Items;
use backend\modules\catalog\models\Orders;
use backend\modules\catalog\models\Sales;
use common\models\User;
use yii\base\Model;
use yii\db\ActiveQuery;
use yii;
use yii\helpers\Json;
use yii\helpers\Url;

class OrderForm extends Model
{
    //region Информация о покупателе
    public $first_name;
    public $surname;
    public $phone;
    public $email;
    //endregion
    //region Адрес доставки
    public $city;
    public $address;
    //endregion
    //region Информация о заказе
    public $type_delivery;
    public $payment;
    public $comments;
    //endregion
    public $isSubscribe;
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            //region Информация о покупателе
            [['first_name', 'email', 'phone'], 'trim'],
            [['first_name', 'phone', 'type_delivery'], 'required'],
            ['email', 'email'],
            //endregion
            //region Адрес доставки
            [['city', 'address'], 'required', 'on' => ['isDelivery']],
            [['city', 'address'], 'string', 'max' => 500],
            //endregion
            //region Информация о заказе
            [['payment'], 'required'],
            [['comments'], 'string', 'max' => 1500],
            [['surname'], 'string', 'max' => 255],
            //endregion
            //region Безопасные аттрибуты, без этого форма не будет принимать
            [['first_name', 'surname', 'email', 'phone', 'city', 'address', 'payment', 'comments','type_delivery','isSubscribe'], 'safe'],
            //endregion
        ];
    }
    /**
     * @inheritdoc
     */
    public function formName()
    {
        return 'order';
    }
    /**
     * @inheritdoc
     */
    public function beforeValidate()
    {
        if ($this->type_delivery == 'courier') {
            $this->scenario = 'isDelivery';
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'first_name' => \Yii::t('main', 'Имя'),
            'surname' => \Yii::t('main', 'Фамилия'),
            'phone' => \Yii::t('main', 'Телефон'),
            'email' => \Yii::t('main', 'E-Mail'),
            'city' => \Yii::t('main', 'Город'),
            'address' => \Yii::t('main', 'Адрес'),
            'type_delivery' => \Yii::t('main', 'Способ доставки'),
            'payment' => \Yii::t('main', 'Способ оплаты'),
            'comments' => \Yii::t('main', 'Комментарий'),
        ];
    }

    public function send()
    {
        /**
         * @var $user \common\models\User
         */
        $result = [];
        $connect = \Yii::$app->db;
        $transaction = $connect->beginTransaction();
        if (\Yii::$app->user->isGuest) {
            if ($this->email && !User::findByUsername($this->email)) {
                $user = new User();
                $entity = [
                    'isSubscription' => $this->isSubscribe,
                ];
                $user->data = Json::encode($entity);
                $user->email = $this->email;
                $user->phone = $this->phone;
                $user->username = $this->first_name ;
                $user->surname = $this->surname;
                $user->patronymic = '';
                $user->status = $user::STATUS_ACTIVE;
                $user->password = \Yii::$app->security->generateRandomString(6);
                $user->generateAuthKey();
                if (!$user->save()) {
                    $result['message']['error'] = 'Произошла ошибка на стороне сервера!';
                    return $result;
                }
            } elseif ($this->phone) {
                $entity = [
                    'isSubscription' => $this->isSubscribe,
                ];
                $attributes_user = [];
                $attributes_user['username'] = $this->first_name;
                $attributes_user['surname'] = $this->surname;
                $attributes_user['patronymic'] = '';
                $attributes_user['email'] = $this->email;
                $attributes_user['data'] =Json::encode($entity);
                $user = User::checkPhone($this->phone, $attributes_user);
            } else {
                $user = null;
            }
        } else {
            $user = \Yii::$app->user->identity;
            $update_user = false;
            if (!$user->phone) {
                $user->phone = $this->phone;
                $update_user = true;
            }
            if ($update_user) {
                $user->save(false);
            }
        }
        $time = time();
        $other_field = [];

        $data = [
            'user_name' => (($this->surname) ? ($this->surname . ' ') : '') . $this->first_name,
            'user_phone' => $this->phone,
            'user_mail' => $this->email,
            'user_comments' => $this->comments,
            'payment' => $this->payment,
            'delivery' => $this->type_delivery,
            'status' => '0_new',
            'user_address' => $this->address,
            'user_city' => $this->city,
            'data' => Json::encode($other_field),
            'created_at' => $time,
            'updated_at' => $time
        ];
        if($user){
            $data['user_id'] = $user->id;
        }
        /**
         * @var $items Items[]
         */
        $order = new Orders();
        $sessions_items = \Yii::$app->session->get('items', []);
        $q = new ActiveQuery(Items::className());
        $q->indexBy('id')
            ->andWhere(['id' => array_keys($sessions_items)]);
        $db_items = $q->all();
        $sum = 0;
        $data_items = [];
        $giftsAdded = Yii::$app->c_cookie->get('gifts', []);

        foreach ($sessions_items as $item_id => $item) {
            if (isset($db_items[$item_id])) {
                $count_item = $item['count'];
                /** @var Items $target_item */
                $target_item = $db_items[$item_id];
                $price = -1;

                if ($giftsAdded && !empty($giftsAdded[$item->id])) {
                    $sale = Sales::find()
                        ->select(['id', 'gifts'])
                        ->where(['active' => 1])
                        ->andWhere(['not', ['gifts' => null]])
                        ->andWhere(['id' => $giftsAdded[$item->id]])
                        ->one();

                    if (!empty($sale)) {
                        foreach ($sale->gifts as $gift) {
                            if ($gift['id'] == $item->id) {
                                $price = $gift['price'];
                                break;
                            }
                        }
                    }
                }

                if ($price > -1) {
                    $item_sum = $price;
                    $priceReal = $price * $item['count'];
                }
                else {
                    $item_sum = $target_item->real_price();
                    $priceReal = $target_item->sum_price($count_item);
                }

                $sum += $priceReal;
                $data_items[] = [
                    'order_id' => '{order_id}',
                    'item_id' => $target_item->id,
                    'count' => $item['count'],
                    'price' => $item_sum,
                    'data' => Json::encode($order->convert_to_array($target_item))
                ];
            }
        }
        $data['full_price'] = $sum;
        if ($connect->createCommand()->insert('orders', $data)->execute() && $data_items) {
            $order_id = $connect->getLastInsertID();
            $data['id'] = $order_id;
            foreach ($data_items as &$order_item) {
                $order_item['order_id'] = $order_id;
            }
            if ($connect->createCommand()->batchInsert('orders_items', [
                'order_id',
                'item_id',
                'count',
                'price',
                'data'
            ], $data_items)
                ->execute()
            ) {
                $url_back = Json::encode(Url::to(['site/success-order']));
                $result['js'] = <<<JS
window.location={$url_back}
JS;
                /**
                 * @var $mailer \yii\swiftmailer\Message
                 */
                $send_mails = explode(',', \Yii::$app->settings->get('admin_email', 'developer@instinct.kz'));
                foreach ($send_mails as $key_email => &$value_email) {
                    if (!($value_email = trim($value_email, " \t\n\r\0\x0B"))) {
                        unset($send_mails[$key_email]);
                    }
                }
                $data_email = [
                    'item' => new Orders($data),
                ];
                \Yii::$app->mailer->compose(['html' => 'admin/order'], $data_email)
                    ->setFrom([\Yii::$app->params['supportEmail'] => \Yii::$app->params['siteName'] . ' info'])
                    ->setTo($send_mails)
                    ->setSubject('Новый заказ на сайте ' . \Yii::$app->params['siteName'])->send();
                if ($data['user_mail']) {
                    \Yii::$app->mailer->compose(['html' => 'order'], ['order' => Orders::findOne($order_id)])
                        ->setFrom([\Yii::$app->params['supportEmail'] => 'Интернет-магазин ' . \Yii::$app->params['siteName'] . '.kz'])
                        ->setTo($data['user_mail'])
                        ->setSubject('Заказ на сайте ' . \Yii::$app->params['siteName'] . '.kz')->send();
                }
                \Yii::$app->session->set('success_order', $order_id);
                \Yii::$app->session->set('items', []);
                $transaction->commit();
            } else {
                $result['message']['error'] = \Yii::t('main', 'Произошла ошибка на стороне сервера!');
                return $result;
            }
        } else {
            $transaction->rollBack();
        }
        return $result;
    }
}