<?php
/**
 * Created by PhpStorm.
 * User: lxShaDoWxl
 * Date: 31.07.15
 * Time: 14:27
 */
/*
public function behaviors(){
    return [
        [
            'class' => '\shadow\behaviors\UploadFileBehavior',
            'attributes' => ['img'],
        ],
    ];
}
*/
namespace shadow\behaviors;

use shadow\SBehavior;
use Yii;
use yii\base\Exception;
use yii\base\InvalidCallException;
use yii\db\ActiveRecord;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\helpers\Inflector;
use yii\helpers\VarDumper;
use yii\web\UploadedFile;

/**
 * Class UploadFileBehavior
 * @package shadow\behaviors
 * @property ActiveRecord $owner
 */
class UploadFileBehavior extends SBehavior
{
    const EVENT_AFTER_FILE_SAVE = 'afterFileSave';
    /** @var array Name of attributes which holds the attachment. */
    public $attributes = array('file');
    /** @var string Основная дерикторию куда записывать */
    public $mainDir = '@web_frontend';
    /** @var string Path template to use in storing files.5 */
    public $filePath = '/[[model]]/[[uniqid]]_[[attribute]].[[extension]]';
    /** @var string Where to store images. */
    public $fileUrl = '/[[model]]/[[uniqid]]_[[attribute]].[[extension]]';
    /**
     * @var string Attribute used to link owner model with it's parent
     * @deprecated Use attribute_xxx placeholder instead
     */
    public $parentRelationAttribute;

    public $copy = 0;
    /**
     * @var ActiveRecord
     */
    protected $copy_model;
    /** @var \yii\web\UploadedFile[] */
    protected $files;
    /**
     * @var boolean
     */
    protected $isValidate = false;
    /**
     * @var boolean
     */
    protected $id_key;
    /**
     * @var array Массив уникального ключа для каждого атрибута
     */
    protected $attributes_uniqid = [];
    /**
     * @inheritdoc
     */
    public function events()
    {
        return [
            ActiveRecord::EVENT_BEFORE_VALIDATE => 'beforeValidate',
            ActiveRecord::EVENT_BEFORE_INSERT => 'beforeSave',
            ActiveRecord::EVENT_BEFORE_UPDATE => 'beforeSave',
            ActiveRecord::EVENT_AFTER_INSERT => 'afterSave',
            ActiveRecord::EVENT_AFTER_UPDATE => 'afterSave',
            ActiveRecord::EVENT_BEFORE_DELETE => 'beforeDelete',
        ];
    }
    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->filePath = $this->mainDir . '/uploads' . $this->filePath;
        $this->fileUrl = '/uploads' . $this->fileUrl;
    }

    /**
     * Before validate event.
     */
    public function beforeValidate()
    {
        $this->isValidate = true;
        $this->initCopyItem();
        foreach ($this->attributes as $attribute) {
            $this->addFiles($attribute);
        }
    }
    public function addFiles($attribute)
    {
        if ($this->owner->{$attribute} instanceof UploadedFile) {
            $this->files[$attribute] = $this->owner->{$attribute};
            return;
        }
        $this->files[$attribute] = UploadedFile::getInstance($this->owner, $attribute);
        if (!isset($this->files[$attribute]) || empty($this->files[$attribute])) {
            $this->files[$attribute] = UploadedFile::getInstanceByName($attribute);
        }
        if ($this->files[$attribute] instanceof UploadedFile) {
            $this->owner->{$attribute} = $this->files[$attribute];
        } elseif ($this->copy_model) {
            $this->attributes_uniqid[$attribute] = uniqid();
            $this->files[$attribute] = $this->copy_model->getAttribute($attribute);
            $this->owner->{$attribute} = $this->copy_model->getAttribute($attribute);
            $this->owner->{$attribute} = $this->resolvePath($this->fileUrl, $attribute);
        }
    }
    private function initCopyItem()
    {
        if ($this->copy) {
            $class_name = get_class($this->owner);
            $this->copy_model = $class_name::findOne($this->copy);
        }
    }
    /**
     * Before save event.
     *
     * @throws \yii\base\InvalidConfigException
     */
    public function beforeSave()
    {
        $oldModel = false;
        foreach ($this->attributes as $attribute) {
            if (!$this->isValidate) {
                $this->addFiles($attribute);
            }
            if ($this->files[$attribute] instanceof UploadedFile) {
                $this->attributes_uniqid[$attribute] = uniqid();
                if (!$this->owner->isNewRecord) {
                    /** @var static $oldModel */
                    if (!$oldModel) {
                        $oldModel = $this->owner->findOne($this->owner->primaryKey);
                    }
                    $oldModel->cleanFile($attribute);
                }
                $this->owner->{$attribute} = $this->resolvePath($this->fileUrl, $attribute);
            } else { // Fix html forms bug, when we have empty file field
                if (!$this->owner->isNewRecord && $this->owner->{$attribute} == 'deleted') {
                    if (!$oldModel) {
                        $oldModel = $this->owner->findOne($this->owner->primaryKey);
                    }
                    $oldModel->cleanFile($attribute);
                    $this->owner->{$attribute} = null;
                } elseif (!$this->owner->isNewRecord && empty($this->owner->{$attribute})) {
                    $old_attribute = ArrayHelper::getValue($this->owner->oldAttributes, $attribute, null);
                    $this->owner->{$attribute} = ($old_attribute ? $old_attribute : null);
                } elseif ($this->owner->isNewRecord && !$this->owner->{$attribute}) {
                    $this->owner->{$attribute} = null;
                }
            }
        }
    }
    /**
     * Removes files associated with attributes
     */
    public function cleanFiles()
    {
        $attr_path = '';
        foreach ($this->attributes as $attribute) {
            if (!$attr_path) {
                $attr_path = $this->cleanFile($attribute);
            } else {
                $this->cleanFile($attribute);
            }
        }
        if ($attr_path) {
            $dir = pathinfo($attr_path, PATHINFO_DIRNAME);
            $count_slash = substr_count($dir, DIRECTORY_SEPARATOR);
            if ($count_slash > 2) {
                FileHelper::removeDirectory(Yii::getAlias($this->mainDir . $dir));
            }
        }
    }
    /**
     * Removes file associated with attribute
     * @param string $attribute
     * @return string
     */
    public function cleanFile($attribute)
    {
        if (isset($this->owner->oldAttributes[$attribute])) {
            $path = Yii::getAlias($this->mainDir . $this->owner->oldAttributes[$attribute]);
            @unlink($path);
            return $this->owner->oldAttributes[$attribute];
        }
        return '';
    }
    /**
     * Replaces all placeholders in path variable with corresponding values
     *
     * @param string $path
     * @param string $attribute
     * @return string
     */
    public function resolvePath($path, $attribute)
    {
        $path = Yii::getAlias($path);
        $pi = pathinfo($this->owner->{$attribute});
        $fileName = ArrayHelper::getValue($pi, 'filename');
        $extension = strtolower(ArrayHelper::getValue($pi, 'extension'));
        $result = preg_replace_callback('|\[\[([\w\_/]+)\]\]|', function ($matches) use ($fileName, $extension, $attribute) {
            $name = $matches[1];
            switch ($name) {
                case 'extension':
                    return $extension;
                case 'filename':
                    return $fileName;
                case 'basename':
                    return $fileName . '.' . $extension;
                case 'app_root':
                    return Yii::getAlias('@app');
                case 'web_root':
                    return Yii::getAlias('@web_frontend');
                case 'base_url':
                    return Yii::getAlias('@web');
                case 'model':
                    $r = new \ReflectionClass($this->owner->className());
                    return Inflector::camel2id($r->getShortName());
                case 'attribute':
                    return lcfirst($attribute);
                case 'id':
                case 'pk':
                    if (!$this->owner->isNewRecord) {
                        $pk = implode('_', $this->owner->getPrimaryKey(true));
                        return lcfirst($pk);
                    } else {
                        return $this->attributes_uniqid[$attribute];
                    }
                case 'uniqid':
                    return $this->attributes_uniqid[$attribute];
                case 'id_path':
                    return static::makeIdPath($this->owner->getPrimaryKey());
                case 'parent_id':
                    return $this->owner->{$this->parentRelationAttribute};
            }
            if (preg_match('|^attribute_(\w+)$|', $name, $am)) {
                $attribute = $am[1];
                return $this->owner->{$attribute};
            }
            return '[[' . $name . ']]';
        }, $path);
        return $result;
    }
    /**
     * @param integer $id
     * @return string
     */
    protected static function makeIdPath($id)
    {
        $id = is_array($id) ? implode('', $id) : $id;
        $length = 10;
        $id = str_pad($id, $length, '0', STR_PAD_RIGHT);
        $result = [];
        for ($i = 0; $i < $length; $i++) {
            $result[] = substr($id, $i, 1);
        }
        return implode('/', $result);
    }
    /**
     * After save event.
     */
    public function afterSave()
    {
        foreach ($this->attributes as $attribute) {
            if ($this->files[$attribute] instanceof UploadedFile) {
                $path = $this->getUploadedFilePath($attribute);
                FileHelper::createDirectory(pathinfo($path, PATHINFO_DIRNAME), 0775, true);
                if (!$this->files[$attribute]->saveAs($path)) {
                    throw new Exception('File saving error.');
                }
                $this->owner->trigger(static::EVENT_AFTER_FILE_SAVE);
            } elseif ($this->copy_model && is_file(Yii::getAlias('@web_frontend') . $this->files[$attribute])) {
                $path = $this->getUploadedFilePath($attribute);
                FileHelper::createDirectory(pathinfo($path, PATHINFO_DIRNAME), 0775, true);
                @copy(Yii::getAlias('@web_frontend') . $this->files[$attribute], $path);
                $this->owner->trigger(static::EVENT_AFTER_FILE_SAVE);
            }
        }
    }
    /**
     * Returns file path for attribute.
     *
     * @param string $attribute
     * @return string
     */
    public function getUploadedFilePath($attribute)
    {
        $behavior = static::getInstance($this->owner, $attribute);
        if (!$this->owner->{$attribute}) {
            return '';
        }
        return $behavior->resolvePath($behavior->filePath, $attribute);
    }
    /**
     * Returns behavior instance for specified class and attribute
     *
     * @param ActiveRecord $model
     * @param string $attribute
     * @return static
     */
    public static function getInstance(ActiveRecord $model, $attribute)
    {
        foreach ($model->behaviors as $behavior) {
            if ($behavior instanceof self && in_array($attribute, $behavior->attributes)) {
                return $behavior;
            }
        }
        throw new InvalidCallException('Missing behavior for attribute ' . VarDumper::dumpAsString($attribute));
    }
    /**
     * Before delete event.
     */
    public function beforeDelete()
    {
        $this->cleanFiles();
    }
    /**
     * Returns file url for the attribute.
     *
     * @param string $attribute
     * @return string|null
     */
    public function getUploadedFileUrl($attribute)
    {
        if (!$this->owner->{$attribute}) {
            return null;
        }
        $behavior = static::getInstance($this->owner, $attribute);
        return $behavior->resolvePath($behavior->fileUrl, $attribute);
    }
}