<?php
/**
 * This is the template for generating the model class of a specified table.
 * DO NOT EDIT THIS FILE! It may be regenerated with Gii.
 *
 * @var yii\web\View $this
 * @var shadow\sgii\model\Generator $generator
 * @var string $tableName full table name
 * @var string $className class name
 * @var yii\db\TableSchema $tableSchema
 * @var string[] $labels list of attribute labels (name => label)
 * @var string[] $rules list of validation rules
 * @var array $relations list of relations (name => relation declaration)
 */

echo "<?php\n";
?>
/**
 * @var $this yii\web\View
 * @var $context <?=$generator->nsController?>\<?=$className?>Controller
 * @var $pages yii\data\Pagination
 * @var $items <?=$generator->ns?>\<?=$className?>[]
 */
use yii\helpers\Inflector;
use yii\helpers\Url;
use yii\widgets\LinkPager;

$context = $this->context;
$url = Inflector::camel2id($context->id);
?>
<?='<?='?> $this->render('//blocks/breadcrumb') ?>
<section id="content">
    <div class="panel">
        <div class="panel-heading">
            <a href="<?='<?='?> Url::to([$url . '/control']) ?>" class="btn-primary btn">
                <i class="fa fa-plus"></i> <span class="hidden-xs hidden-sm">Добавить</span></a>
        </div>
        <div class="panel-body">
            <table class="table-primary table table-striped table-hover">
                <colgroup>
                    <col width="25px">
                    <col>
                    <col width="25px">
                </colgroup>
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Название</th>
                    <th class="text-right">Действия</th>
                </tr>
                </thead>
                <tbody>
                <?='<?php'?> foreach ($items as $item): ?>
                    <tr id="layout_normal">
                        <td><?='<?='?> $item->id ?></td>
                        <td>
                            <a href="<?='<?='?> Url::to([$url . '/control', 'id' => $item->id]) ?>"><?='<?='?> $item->name ?></a>
                        </td>
                        <td class="actions text-right">
                            <a href="<?='<?='?> Url::to([$url . '/control', 'id' => $item->id]) ?>" class="btn-success btn-xs btn">
                                <i class="fa fa-pencil fa-inverse"></i>
                            </a>
                            <?='<?'?> if (!$item->getAttribute('not_delete')): ?>
                                <a href="<?='<?='?> Url::to([$url . '/deleted', 'id' => $item->id]) ?>" class="btn-danger btn-xs btn-confirm btn">
                                    <i class="fa fa-times fa-inverse"></i>
                                </a>
                            <?='<?'?> endif ?>
                        </td>
                    </tr>
                <?='<?php'?> endforeach; ?>
                </tbody>
            </table>
        </div>
        <div class="panel-footer">
            <?='<?='?> LinkPager::widget([
                'pagination' => $pages,
            ]);
            ?>
        </div>
    </div>
</section>