<?php
namespace shadow\plugins\seo;

use yii\base\Component;

class SSeo extends Component
{
    public $enable = true;
    public $enableRule = true;

    /**
     * Настройки для SEO
     * @var array
     */
    public $resizes_imgs = [
        'item_320',
        'item_920',
        'item_1220'
    ];

    /**
     * @var string resource_id from table
     */
    public $keyGet = 'id';
    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init()
    {
        if ($this->enableRule) {
            if(\Yii::$app->id=='app-frontend'){
                \Yii::$app->urlManager->addRules(
                    [
                        [
                            'class' => SClearUrlRule::className()
                        ],
                        [
                            'class' => SUrlRule::className()
                        ],
                    ],
                    false
                );
            }else{
                \Yii::$app->urlManagerFrontEnd->addRules(
                    [
                        [
                            'class' => SClearUrlRule::className()
                        ],
                        [
                            'class' => SUrlRule::className()
                        ],
                    ],
                    false
                );
            }

        }
        parent::init(); // TODO: Change the autogenerated stub
    }
    public function correctionUrl($url)
    {
        // Слэш в конце
        if (substr($url, -1) == '/') {
            $url = trim($url, '/');
        }
        // Двойной слэш
        if (strpos($url, '//') !== false) {
            $url = str_replace('//', '/', $url);
        }
        // Символы в верхнем регистре
        if (($tmpUrl = strtolower($url)) !== $url) {
            $url = $tmpUrl;
        }
        return $url;
    }
}