<?php
namespace shadow\plugins\yml\console\controllers;

use backend\modules\catalog\models\Items;
use yii\console\Controller;

/**
 * Class YmlController
 * @package shadow\plugins\yml\console\controllers
 */
class YmlController extends Controller
{
    protected $config_file;
    protected $yii_console;
    protected $debug = false;
    /**
     * Initializes the object.
     * This method is invoked at the end of the constructor after the object is initialized with the
     * given configuration.
     */
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->config_file = \Yii::getAlias('@yml_config/main.php');
        $this->yii_console = \Yii::getAlias('@app/..') . DIRECTORY_SEPARATOR . 'yii';
    }

    public function actionStart($size_offers = 500, array $exclude_cats = [])
    {
        \Yii::info('start yml', 'YmlController');
        $q = Items::find()->andWhere(['isVisible' => 1]);
        if ($exclude_cats) {
            $q->andWhere(['not in', 'cid', $exclude_cats]);
        }
        $count = $q->count();
        $count_xml = ceil($count / $size_offers);
        if ($count_xml) {
            if ($exclude_cats) {
                $exclude_cats = implode(',', $exclude_cats);
                if ($this->debug) {
                    $output = shell_exec("$this->yii_console yml/offers $size_offers $count_xml 1 $exclude_cats --appconfig={$this->config_file} 2>&1");
                    \Yii::error($output, 'YmlController');
                } else {
                    exec("$this->yii_console yml/offers $size_offers $count_xml 1 $exclude_cats --appconfig={$this->config_file} > /dev/null &");
                }
            } else {
                if ($this->debug) {
                    $output = shell_exec("$this->yii_console yml/offers $size_offers $count_xml 1 --appconfig={$this->config_file} 2>&1");
                    \Yii::error($output, 'YmlController');
                } else {
                    exec("$this->yii_console yml/offers $size_offers $count_xml 1 --appconfig={$this->config_file} > /dev/null &");
                }
            }
        }
    }
    public function actionOffers($size_offers, $count_xml, $number, array $exclude_cats = [])
    {
        \Yii::info('start yml offers', 'YmlController');
        if ($number == 1) {
            $offset = 0;
        } else {
            $offset = $size_offers * ($number - 1);
        }
        $result = \Yii::$app->yml->offers($size_offers, $offset, $exclude_cats);
        if ($result) {
            $number++;
            if ($exclude_cats) {
                $exclude_cats = implode(',', $exclude_cats);
                exec("$this->yii_console yml/offers $size_offers $count_xml $number $exclude_cats --appconfig={$this->config_file} > /dev/null &");
            } else {
                exec("$this->yii_console yml/offers $size_offers $count_xml $number --appconfig={$this->config_file} > /dev/null &");
            }
        } else {
            \Yii::$app->yml->end();
        }
    }
}