<?php
/**
 * Created by PhpStorm.
 * Project: kingfisher
 * User: lxShaDoWxl
 * Date: 31.10.15
 * Time: 17:07
 */
namespace backend\models;

use shadow\multilingual\behaviors\MultilingualBehavior;
use shadow\multilingual\behaviors\MultilingualQuery;
use Yii;
use yii\caching\TagDependency;
use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\helpers\Url;

/**
 *
 * @property integer $id
 * @property string $name
 * @property string $type
 * @property integer $owner_id
 * @property string $url
 * @property integer $isVisible
 * @property integer $sort
 * @property integer $parent_id
 *
 * @property BaseMenu $parent
 * @property BaseMenu[] $menus
 */
class BaseMenu extends \shadow\SActiveRecord
{
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name'], 'required'],
            [['owner_id', 'isVisible', 'sort', 'parent_id'], 'integer'],
            [['name'], 'string', 'max' => 255],
            [['type'], 'string', 'max' => 50],
            [['url'], 'string', 'max' => 500],
            [['module', 'page'], 'integer'],
            [['module', 'page'], 'safe'],
            [['module'], 'required', 'on' => ['module']],
            [['page'], 'required', 'on' => ['page']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        $result = [
            'id' => 'ID',
            'name' => 'Название',
            'type' => 'Тип',
            'owner_id' => 'Owner ID',
            'url' => 'Ссылка',
            'isVisible' => 'Видимость',
            'sort' => 'Порядок',
            'parent_id' => 'Родитель',
            'module' => 'Модуль',
            'page' => 'Страница',
        ];
        /**@var $ml MultilingualBehavior */
        if ($ml = $this->getBehavior('ml')) {
            $ml->attributeLabels($result);
        }
        return $result;
    }
    public static function find()
    {
        if (Yii::$app->function_system->enable_multi_lang()) {
            $q = new MultilingualQuery(get_called_class());
            if (Yii::$app->id == 'app-backend') {
                $q->multilingual();
            } else {
                $q->localized();
            }
            return $q;
        } else {
            return parent::find();
        }
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getParent()
    {
        return $this->hasOne($this::className(), ['id' => 'parent_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMenus()
    {
        $result = $this->hasMany($this::className(), ['parent_id' => 'id'])->orderBy(['sort' => SORT_ASC]);
        if(Yii::$app->id != 'app-backend'){
            $result->andWhere(['isVisible' => 1]);
        }
        return $result;
    }
    public function beforeValidate()
    {
        if ($this->type) {
            $this->owner_id = $this->{$this->type};
            $this->scenario = $this->type;
        } else {
            $this->owner_id = null;
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }
    public function beforeSave($insert)
    {
        if (!$this->parent_id || $this::$no_parent) {
            $this->parent_id = null;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public $module;
    public $page;

    public $data_types = [
        '' => 'Пустое',
        'page' => 'Текстовая страница',
        'module' => 'Модуль'
    ];
    public static $no_parent = false;
    public function FormParams()
    {
        $form_name = strtolower($this->formName());
        Yii::$app->getView()->registerJs(<<<JS
$('#{$form_name}-type').on('change',function() {
var val=$(this).val();
  $('.field-{$form_name}-page').hide();
  $('.field-{$form_name}-module').hide();
  $('.field-{$form_name}-'+val).show();
})
JS
        );
        $fields = [
            'name' => [],
            'parent_id' => [
                'relation' => [
                    'class' => $this::className(),
                    'query' => [
                        'where' => ['parent_id' => null]
                    ]
                ]
            ],
            'type' => [
                'type' => 'dropDownList',
                'data' => $this->data_types,
            ],
            'module' => [
                'relation' => [
                    'class' => Module::className(),
                ],
                'field_options' => [
                    'options' => ['style' => ($this->type == 'module') ? '' : 'display:none'],
                ]
            ],
            'page' => [
                'relation' => [
                    'class' => Pages::className(),
                ],
                'field_options' => [
                    'options' => ['style' => ($this->type == 'page') ? '' : 'display:none'],
                ]
            ],
        ];
        if ($this->isNewRecord) {
            $this->loadDefaultValues(true);
        } else {
            if ($this->type) {
                $this->{$this->type} = $this->owner_id;
            }
            if ($this->menus) {
                unset($fields['parent_id']);
            } else {
                $q_patent = $fields['parent_id']['relation']['query']['where'];
                $fields['parent_id']['relation']['query']['where'] = ['and', $q_patent, ['<>', 'id', $this->id]];
            }
        }
        $controller_name = Inflector::camel2id(Yii::$app->controller->id);
        if ($this::$no_parent) {
            unset($fields['parent_id']);
        }
        $result = [
            'form_action' => [$controller_name . '/save'],
            'cancel' => ["$controller_name/index"],
            'fields' => [
                'isVisible' => [
                    'type' => 'checkbox'
                ],
                'sort' => [],
            ],
            'groups' => [
                'main' => [
                    'title' => 'Основное',
                    'icon' => 'suitcase',
                    'options' => [],
                    'fields' => $fields,
                ],
            ]
        ];
        if ($this->getBehavior('ml')) {
            $this->ParamsLang($result, $fields);
        }
        return $result;
    }
    public $data_status = array(
        0 => 'Скрыто',
        1 => 'Опубликовано',
    );
    public function status()
    {
        return $this->data_status[$this->isVisible];
    }
    public static function getListItems($model = null)
    {
        /**
         * @var $items self[]
         */
        $controller_name = Inflector::camel2id(Yii::$app->controller->id);
        if ($model == null) {
            $model = new Menu();
        }
        $result['columns'] = [
            'status' => [
                'function' => function ($item) {
                    return Html::tag('span', $item->status(), ['class' => 'label label-success editable-status editable editable-click', 'data-id' => $item->id]);
                }
            ]
        ];
        $result['controls'] = [
//            'add_parent' => [
//                'url' => ['footer-menu/control', 'parent' => '{id}'],
//                'icon' => 'plus',
//                'options' => [
//                    'class' => 'btn-success btn-xs btn'
//                ]
//            ],
            'deleted' => [
                'url' => ["$controller_name/deleted", 'id' => '{id}'],
                'icon' => 'times fa-inverse',
                'options' => [
                    'class' => 'btn-xs btn-confirm btn-danger'
                ]
            ]
        ];
        $items = $model::find()->orderBy('`sort` ASC')->where(['parent_id' => null])->with('menus')->all();
        foreach ($items as $item) {
            $sub_items = [];
            if ($item->menus) {
                foreach ($item->menus as $sub_item) {
                    $sub_items[$sub_item->id] = [
                        'model' => $sub_item,
                        'link' => [
                            'title' => $sub_item->name,
                            'url' => ["$controller_name/control", 'id' => $sub_item->id],
                        ]
                    ];
                    $sub_sub_items = [];
                    if($sub_item->menus){
                        foreach ($sub_item->menus as $sub_sub_item) {
                            $sub_sub_items[$sub_sub_item->id] = [
                                'model' => $sub_sub_item,
                                'link' => [
                                    'title' => $sub_sub_item->name,
                                    'url' => ["$controller_name/control", 'id' => $sub_sub_item->id],
                                ]
                            ];

                        }
                    }
                    if($sub_sub_items){
                        $sub_items[$sub_item->id]['items'] = $sub_sub_items;
                    }
                }
            }
            $result['items'][$item->id] = [
                'model' => $item,
                'link' => [
                    'title' => $item->name,
                    'url' => ["$controller_name/control", 'id' => $item->id],
//                    'prev'=>'site/'.$item->url,
                ],
                'items' => $sub_items
            ];
        }
        return $result;
    }
    public function createUrl()
    {
        /**
         * @var $module Module
         */
        $result = 'javascript:void(0)';
        if ($this->type) {
            switch ($this->type) {
                case 'page':
                    $result = Url::to(['site/page', 'id' => $this->owner_id]);
                    break;
                case 'module':
                    $modules = Module::getDb()->cache(
                        function ($db) {
                            return Module::find()->indexBy('id')->all();
                        },
                        3600,
                        new TagDependency(['tags' => 'db_caching_module'])
                    );
                    $module = (isset($modules[$this->owner_id]) ? $modules[$this->owner_id] : false);
                    if ($module) {
                        $result = Url::to([$module->action]);
                    }
                    break;
            }
        }
        return $result;
    }
    public function saveClear($event)
    {
        \yii\caching\TagDependency::invalidate(Yii::$app->frontend_cache, $this->tableName() . '_model');
        parent::saveClear($event); // TODO: Change the autogenerated stub
    }
}