<?php
/**
 * Created by PhpStorm.
 * Project: morkovka
 * User: lxShaDoWxl
 * Date: 12.10.15
 * Time: 9:53
 */

namespace backend\models;


use backend\modules\catalog\models\DeliveryPrice;
use common\models\User;
use Yii;
use yii\helpers\ArrayHelper;
use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\helpers\Json;

class EditUser extends User
{
    public $new_password;
    public $entity_nds;
    public $entity_name;
    public $entity_address;
    public $entity_bin;
    public $entity_iik;
    public $entity_bank;
    public $entity_bik;

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $rules = [
            [['new_password'], 'trim'],
            [['username'], 'required'],
            [['isEntity', 'manager_id', 'city_id'], 'integer'],
            [['discount', '!bonus'], 'number'],
            [['isEntity', '!bonus', 'isWholesale'], 'default', 'value' => 0],
            [
                ['new_password'],
                'match',
                'pattern' => '/^[A-Za-z0-9_!@#$%^&*()+=?.,]+$/u',
                'message' => 'Не допустимые символы',
            ],
            [['new_password'], 'string', 'length' => [4, 255]],
            ['email', 'email'],
            [['phone'], 'match', 'pattern' => '/^((\+?7)(\(?\d{3})\)-?)?(\d{3})(-?\d{4})$/', 'message' => \Yii::t('main', 'Некорректный формат поля {attribute}')],
            [['username', 'phone'], 'string', 'max' => 255],
            [['username', 'phone'], 'safe'],
            ['entity_nds', 'boolean', 'on' => ['entity']],
            [['entity_name', 'entity_address', 'entity_bin', 'entity_iik', 'entity_bank', 'entity_bik',], 'string', 'max' => 255, 'on' => ['entity']],
            [['entity_name', 'entity_address', 'entity_bin', 'entity_iik', 'entity_bank', 'entity_bik', 'entity_nds', 'status'], 'safe'],
        ];
        if ($this->isNewRecord) {
            $rules[] = ['phone', 'unique',
                'targetClass' => User::className(),
                'targetAttribute' => 'phone',
            ];
            $rules[] = ['email', 'unique',
                'targetClass' => User::className(),
                'targetAttribute' => 'email'
            ];
        } else {
            $rules[] = ['phone', 'unique',
                'targetClass' => User::className(),
                'targetAttribute' => 'phone', 'filter' => ['<>', 'id', $this->id],
            ];
            $rules[] = ['email', 'unique',
                'targetClass' => User::className(),
                'targetAttribute' => 'email', 'filter' => ['<>', 'id', $this->id]];
        }
        return $rules;
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Имя',
            'email' => 'E-Mail',
            'phone' => 'Телефон',
            'bonus' => 'Бонусов',
            'code' => 'Реферальный код',
            'new_password' => 'Новый пароль',
            'isEntity' => 'Юр. лицо',
            'manager_id' => 'Менеджер',
            'discount' => 'Скидка',
            'isWholesale' => 'Оптовый',
            'entity_name' => 'Юр. название',
            'entity_address' => 'Юр. адрес',
            'entity_bin' => 'БИН',
            'entity_iik' => 'ИИК',
            'entity_bank' => 'Банк',
            'entity_bik' => 'БИК',
            'entity_nds' => 'Плательщик НДС',
            'city_id' => 'Город',
            'status' => 'Активирован',
        ];
    }

    /**
     * This method is invoked before validation starts.
     * The default implementation raises a `beforeValidate` event.
     * You may override this method to do preliminary checks before validation.
     * Make sure the parent implementation is invoked so that the event can be raised.
     * @return boolean whether the validation should be executed. Defaults to true.
     * If false is returned, the validation will stop and the model is considered invalid.
     */
    public function beforeValidate()
    {
        if ($this->isEntity == 1) {
            $this->scenario = 'entity';
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {
        if ($this->new_password) {
            $this->password = $this->new_password;
        }
        if ($this->isEntity == 1) {
            $entity = [
                'entity_name' => $this->entity_name,
                'entity_address' => $this->entity_address,
                'entity_bin' => $this->entity_bin,
                'entity_iik' => $this->entity_iik,
                'entity_bank' => $this->entity_bank,
                'entity_bik' => $this->entity_bik,
                'entity_nds' => ($this->entity_nds) ? 1 : 0,
            ];
            $this->data = Json::encode($entity);
        }
        if ($this->isNewRecord) {
            $this->generateAuthKey();
            $this->status = self::STATUS_ACTIVE;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function FormParams()
    {
        if ($this->isEntity) {
            $entity = Json::decode($this->data);
            if (is_array($entity)) {
                foreach ($entity as $key => $value) {
                    $this->{$key} = $value;
                }
            }
        }
        if ($this->isNewRecord) {
            $this->loadDefaultValues(true);
            /**@var $user \backend\models\SUser */
            $user = Yii::$app->user->identity;
            if ($user->role == 'manager') {
                $this->manager_id = $user->id;
            }
        }
        $controller_name = Inflector::camel2id(Yii::$app->controller->id);
        $result = [
            'form_action' => [$controller_name . '/save'],
            'cancel' => [$controller_name . '/index'],
            'groups' => [
                'main' => [
                    'title' => 'Основное',
                    'icon' => 'suitcase',
                    'options' => [],
                    'fields' => [
                        'status' => [
                            'type' => 'checkbox',
                            'params' => [
                                'value' => $this::STATUS_ACTIVE
                            ]
                        ],
                        'username' => [],
                        'email' => [],
                        'phone' => [
                            'widget' => [
                                'class' => \yii\widgets\MaskedInput::className(),
                                'config' => [
                                    'mask' => '+7(999)-999-9999',
                                    'definitions' => [
                                        'maskSymbol' => '_'
                                    ],
                                ]
                            ]
                        ],
                        'isEntity' => [
                            'type' => 'checkbox'
                        ],
                        'isWholesale' => [
                            'type' => 'checkbox'
                        ],
                        'bonus' => [],
                        'discount' => [],
                        'manager_id' => [
                            'type' => 'dropDownList',
                            'data' => ArrayHelper::merge(
                                ['' => "Нет"],
                                SUser::find()->where(['role' => 'manager'])->select(['username', 'id'])->indexBy('id')->column()
                            ),
                        ],
                        'city_id' => [
                            'type' => 'dropDownList',
                            'data' => ArrayHelper::merge(
                                ['' => "Нет"],
                                DeliveryPrice::find()->select(['name', 'id'])->indexBy('id')->column()
                            ),
                        ],
//                        'code' => [
//                            'field_options' => [
//                                'inputOptions' => [
//                                    'disabled' => true
//                                ]
//                            ]
//                        ],
                        'new_password' => [
                            'type' => 'password',
                            'field_options' => [
                                'inputOptions' => [
                                    'autocomplete' => "off"
                                ]
                            ]
                        ],
                    ],
                ],
                'company' => [
                    'title' => 'Юр. иформация',
                    'icon' => 'building',
                    'options' => [
                        'class' => ($this->isEntity == 1) ? '' : 'hide'
                    ],
                    'fields' => [
                        'entity_name' => [],
                        'entity_address' => [],
                        'entity_bin' => [],
                        'entity_iik' => [],
                        'entity_bank' => [],
                        'entity_bik' => [],
                        'entity_nds' => [
                            'type' => 'checkbox'
                        ]
                    ]
                ],
                'history_order' => [
                    'title' => 'История заказов',
                    'icon' => 'shopping-cart',
                    'options' => [],
                    'render' => [
                        'view' => 'history_order',
                        'data' => [
                            'user' => $this,
                        ]
                    ]
                ],
                'address_user' => [
                    'title' => 'Адреса',
                    'icon' => 'location-arrow',
                    'options' => [],
                    'render' => [
                        'view' => 'address_user',
                        'data' => [
                            'user' => $this,
                        ]
                    ]
                ],
            ]
        ];
        $form_name = strtolower($this->formName());
        \Yii::$app->view->registerJs(<<<JS
$('#{$form_name}-isentity').on('change', function () {

    if ($(this).prop('checked')) {
        $('#page-company-panel-li').removeClass('hide');
    } else {
        $('#page-company-panel-li').addClass('hide');
    }
});
JS
        );
        return $result;
    }
}