<?php

namespace backend\models;

use shadow\SSettings;
use shadow\widgets\CKEditor;
use yii\bootstrap\Html;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\helpers\Inflector;
use yii\helpers\Json;
use yii\web\UploadedFile;

/**
 * Class EditSettings
 * @package backend\models
 *
 * @property array $data
 */
class EditSettings extends Settings
{
    public function FormParams()
    {
        /**
         * @var $settings Settings[]
         */
        $settings = Settings::find()->all();
        $old_settings = [];

        foreach ($settings as $item) {
            if (isset($this->data[$item->key])) {
                $params_data = $this->data[$item->key];
                $old_settings[$item->key] = $item->value;
                if (isset($params_data['lang'])) {
                    foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                        if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                            $old_settings[$item->key . '_' . $key_lang] = $item->{'value_' . $key_lang};
                        }
                    }
                }
            }
        }

        if ($old_settings) {
            $this->setOldAttributes($old_settings);
            $this->setAttributes($old_settings);
        }

        $groups = [];

        foreach ($this->data as $key => $val) {
            $group_key = (isset($val['group']) ? $val['group'] : 'main');
            $params = (isset($val['params']) ? $val['params'] : []);

            if (!isset($groups[$group_key])) {
                $groups[$group_key] = $this->groups[$group_key];
                $groups[$group_key]['fields'] = [];
            }

            $groups[$group_key]['fields'][$key] = $params;

            if (isset($val['lang'])) {
                $groups[$group_key]['fields'][$key]['field_options']['options'] = [
                    'data' => [
                        'lang' => \Yii::$app->params['defaultLanguage']
                    ]
                ];

                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $groups[$group_key]['fields'][$key . '_' . $key_lang] = $params;
                        $groups[$group_key]['fields'][$key . '_' . $key_lang]['field_options']['options'] = [
                            'data' => [
                                'lang' => $key_lang
                            ],
                            'style' => 'display:none;'
                        ];
                    }
                }
            }
        }

        $result = [
            'form_action' => ['settings/save'],
//            'cancel' => ['settings/control'],
            'groups' => $groups
        ];
        return $result;
    }

    protected $groups = [
        'main' => [
            'title' => 'Основное',
            'icon' => 'suitcase',
            'options' => [],
        ],
        'maps' => [
            'title' => 'Карта',
            'icon' => 'globe',
            'options' => [],
        ],
        'main_text' => [
            'title' => 'Текста',
            'icon' => 'file-text',
            'options' => [],
        ],
        'success_text' => [
            'title' => 'Оповещения',
            'icon' => 'exclamation',
            'options' => [],
        ],
        'soc_url' => [
            'title' => 'Ссылки соц. сетей',
            'icon' => 'share-square',
            'options' => [],
        ],
        'files' => [
            'title' => 'Файлы',
            'icon' => 'picture-o',
            'options' => [],
        ],
        'delivery' => [
            'title' => 'Доставка',
            'icon' => 'truck',
            'options' => [],
        ],
        'delivery_postexpress_tarifs' => [
            'title' => 'PostExpress',
            'icon' => 'truck',
            'options' => [],
        ],
        'delivery_kazpost' => [
            'title' => 'KazPost',
            'icon' => 'truck',
            'options' => [],
        ],
        'address_pickup' => [
            'title' => 'Адрес для вывоза посылок',
            'icon' => 'truck',
            'options' => [],
        ],
        'payment_type' => [
            'title' => 'Виды оплаты',
            'icon' => 'money',
            'options' => [],
        ],
//        'seo_template' => [
//            'title' => 'SEO шаблон',
//            'icon' => 'eye',
//            'options' => [],
//        ],
        'microdata' => [
            'title' => 'SEO микроразметка',
            'icon' => 'search',
            'options' => [],
        ],
    ];

    /**
     * @inheritdoc
     */
    public function __get($name)
    {
        if ($name == 'data') {
            return $this->getData();
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    public function getData()
    {
        return [
            'admin_email' => [
                'group' => 'main',
                'params' => [],
                'name' => 'Почта администратора'
            ],
            'service_scripts' => [
                'name' => 'Сервисные скрипты',
                'group' => 'main',
                'params' => [
                    'type' => 'textArea'
                ],
            ],
            'facebook_soc_url' => [
                'group' => 'soc_url',
                'params' => [],
                'name' => 'Facebook'
            ],
            'vk_soc_url' => [
                'group' => 'soc_url',
                'params' => [],
                'name' => 'Vk'
            ],
            'twitter_soc_url' => [
                'group' => 'soc_url',
                'params' => [],
                'name' => 'Twitter'
            ],
            'youtube_soc_url' => [
                'group' => 'soc_url',
                'params' => [],
                'name' => 'Youtube'
            ],
            'odnoklassniki_soc_url' => [
                'group' => 'soc_url',
                'params' => [],
                'name' => 'Одноклассники'
            ],
            'instagram_soc_url' => [
                'group' => 'soc_url',
                'params' => [],
                'name' => 'Instagram'
            ],
            'map_coordinates_center' => [
                'group' => 'maps',
                'params' => [],
                'name' => 'Координаты центра'
            ],
            'map_contacts_zoom' => [
                'group' => 'maps',
                'params' => [],
                'name' => 'Zoom'
            ],
            'map_coordinates' => [
                'group' => 'maps',
                'params' => [],
                'name' => 'Координаты точки'
            ],
//            'seo_template_title_cat' => [
//                'name' => 'Title Категории',
//                'group' => 'seo_template',
//                'params' => [
//                    'type' => 'textArea'
//                ],
//            ],
//            'seo_template_description_cat' => [
//                'name' => 'Description Категории',
//                'group' => 'seo_template',
//                'params' => [
//                    'type' => 'textArea'
//                ],
//            ],
//            'seo_template_title_item' => [
//                'name' => 'Title Товара',
//                'group' => 'seo_template',
//                'params' => [
//                    'type' => 'textArea'
//                ],
//            ],
//            'seo_template_description_item' => [
//                'name' => 'Description Товара',
//                'group' => 'seo_template',
//                'params' => [
//                    'type' => 'textArea'
//                ],
//            ],
            'min_price_delivery' => [
                'name' => 'Минимальная сумма заказа',
                'group' => 'delivery',
                'params' => [],

            ],
            'max_price_delivery' => [
                'name' => 'Максимальная сумма заказа',
                'group' => 'delivery',
                'params' => [],

            ],
            'price_delivery' => [
                'name' => 'Стоимость доставки для всех',
                'group' => 'delivery',
                'params' => [],
            ],
            'delivery_method_dhl' => [
                'name' => 'Доставка службой DHL',
                'group' => 'delivery',
                'params' => [
                    'type' => 'checkbox',
                ]
            ],
            'delivery_method_dhl_text' => [
                'name' => 'Доставка службой DHL (текст)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ]
            ],
            'delivery_method_kazpost_1' => [
                'name' => 'Доставка службой KazPost (Посылка РК)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'checkbox',
                ]
            ],
            'delivery_method_kazpost_1_text' => [
                'name' => 'Доставка службой KazPost (Посылка РК) (текст)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ]
            ],
            'delivery_method_kazpost_2' => [
                'name' => 'Доставка службой KazPost (Посылка СНГ/ДЗ)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'checkbox',
                ]
            ],
            'delivery_method_kazpost_2_text' => [
                'name' => 'Доставка службой KazPost (Посылка СНГ/ДЗ) (текст)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ]
            ],
            'delivery_method_postexpress_1' => [
                'name' => 'Доставка службой PostExpress (Дверь-Отделение)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'checkbox',
                ]
            ],
            'delivery_method_postexpress_1_text' => [
                'name' => 'Доставка службой PostExpress (Дверь-Отделение) (текст)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ]
            ],
            'delivery_method_postexpress_2' => [
                'name' => 'Доставка службой PostExpress (Дверь-Дверь)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'checkbox',
                ]
            ],
            'delivery_method_postexpress_2_text' => [
                'name' => 'Доставка службой PostExpress (Дверь-Дверь) (текст)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ]
            ],
            'delivery_method_pickup' => [
                'name' => 'Самовывоз',
                'group' => 'delivery',
                'params' => [
                    'type' => 'checkbox',
                ]
            ],
            'delivery_method_pickup_text' => [
                'name' => 'Самовывоз (текст)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ]
            ],
            'delivery_method_courier_1' => [
                'name' => 'Доставка курьером 1',
                'group' => 'delivery',
                'params' => [
                    'type' => 'checkbox',
                ]
            ],
            'delivery_method_courier_1_text' => [
                'name' => 'Доставка курьером 1 (текст)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ]
            ],
            'delivery_method_courier_2' => [
                'name' => 'Доставка курьером 2',
                'group' => 'delivery',
                'params' => [
                    'type' => 'checkbox',
                ]
            ],
            'delivery_method_courier_2_text' => [
                'name' => 'Доставка курьером 2 (текст)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ]
            ],
            'delivery_method_courier_3' => [
                'name' => 'Доставка курьером 3',
                'group' => 'delivery',
                'params' => [
                    'type' => 'checkbox',
                ]
            ],
            'delivery_method_courier_3_text' => [
                'name' => 'Доставка курьером 3 (текст)',
                'group' => 'delivery',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ]
            ],
            'postexpress_tarifs' => [
                'name' => 'Тарифы службы доставки PostExpress',
                'group' => 'delivery_postexpress_tarifs',
                'params' => [
                    'type' => 'postexpressTarifs',
                ]
            ],
            'postexpress_tarifs_price' => [
                'name' => 'Стоимость по зонам',
                'group' => 'delivery_postexpress_tarifs',
                'params' => [
                    'type' => 'postexpressTarifsPrice',
                ]
            ],
            'delivery_kazpost_days' => [
                'name' => 'Количество дней',
                'group' => 'delivery_kazpost',
                'params' => [
                    'type' => 'kazPostDays',
                ]
            ],
            'address_pickup_zip' => [
                'name' => 'Почтовый индекс',
                'group' => 'address_pickup',
                'params' => []
            ],
            'address_pickup_city' => [
                'name' => 'Город',
                'group' => 'address_pickup',
                'params' => []
            ],
            'payment_type_cash' => [
                'name' => 'Наличные',
                'group' => 'payment_type',
                'params' => [],
            ],
            'payment_type_online' => [
                'name' => 'Онлайн оплата',
                'group' => 'payment_type',
                'params' => [],
            ],
            'payment_type_cards' => [
                'name' => 'Банковской картой',
                'group' => 'payment_type',
                'params' => [],
            ],
            'main_phone' => [
                'group' => 'main_text',
                'params' => [],
                'name' => 'Основной телефон'
            ],
            'contact_text' => [
                'group' => 'main_text',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'extraAllowedContent' => 'span',
                                'shiftEnterMode' => 2,
                            ]
                        ]
                    ],
                ],
                'name' => 'Текст в контактах'
            ],
            'name_organization' => [
                'group' => 'microdata',
                'params' => [],
                'name' => 'На главной: Наименование организации'
            ],
            'telephone' => [
                'group' => 'microdata',
                'params' => [],
                'name' => 'На главной: Телефон'
            ],
            'address_region' => [
                'group' => 'microdata',
                'params' => [],
                'name' => 'На главной: Страна'
            ],
            'address_locality' => [
                'group' => 'microdata',
                'params' => [],
                'name' => 'На главной: Город'
            ],
            'street_address' => [
                'group' => 'microdata',
                'params' => [],
                'name' => 'На главной: Улица'
            ],
            'postal_code' => [
                'group' => 'microdata',
                'params' => [],
                'name' => 'На главной: Почтовый индекс'
            ],
        ];
    }

    public $id = null;

    /**
     * @inheritdoc
     */
    public function formName()
    {
        return 'settings'; // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributes()
    {
        $result = [];
        foreach ($this->data as $key => $item) {
            $result[] = $key;
            if (isset($item['lang'])) {
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $result[] = $key . '_' . $key_lang;
                    }
                }
            }
        }
        return $result;
    }

    protected $_attribute_labels = false;

    public function attributeLabels()
    {
        $labels = [];
        if ($this->_attribute_labels === false) {
            foreach ($this->data as $key => $val) {
                if (isset($val['name'])) {
                    $name = $val['name'];
                    $labels[$key] = $name;
                    if (isset($val['lang']) && $val['lang']) {
                        foreach (\Yii::$app->params['languages'] as $language => $label) {
                            $labels[$key . '_' . $language] = $name . ' ' . $label;
                        }
                    }
                }
            }
            $this->_attribute_labels = $labels;
        } else {
            $labels = $this->_attribute_labels;
        }
        return $labels;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $result = [];

        foreach ($this->data as $key => $val) {
            $rule = (isset($val['rule'])) ? $val['rule'] : ([[$key], 'string']);

            $result[] = $rule;
            if (isset($val['lang'])) {
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $result[] = (isset($val['rule'])) ? $val['rule'] : ([[$key . '_' . $key_lang], 'string']);;
                    }
                }
            }
        }

        return $result;
    }

    /**
     * @inheritdoc
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        /**
         * @var $settings Settings
         */
        $settings = Settings::find()->indexBy('key')->all();
        $attributes = $this->data;

        $attributes_values = [];
        foreach ($attributes as $key_attribute => $attribute) {
            $value_attr = $this->getAttribute($key_attribute);
            $val = $this->saveAttribute($key_attribute, $value_attr, (isset($attribute['params']) ? $attribute['params'] : []), $settings);
            $attribute_val = [
                'group' => (isset($attribute['group'])) ? $attribute['group'] : 'main',
                'key' => $key_attribute,
                'value' => $val
            ];
            if (isset($attribute['lang'])) {
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $name = $key_attribute . '_' . $key_lang;
                        $value_attr = $this->getAttribute($name);
                        $val = $this->saveAttribute($name, $value_attr, $attribute);
                        $attribute_val['value_' . $key_lang] = $val;
                    }
                }
            }
            $attributes_values[$key_attribute] = $attribute_val;
        }
        /**
         * @var $record Settings
         */
        foreach ($attributes_values as $key => $attributes_value) {
            if (isset($settings[$key])) {
                $record = $settings[$key];
                $update = false;
                foreach ($attributes_value as $key_name => $value) {
                    if ($record->{$key_name} != $value | $record->{$key_name} == null) {
                        $record->{$key_name} = $value;
                        $update = true;
                    }
                }
                if ($update) {
                    $record->save(false);
                }
            } else {
                $record = new Settings();
                $record->setAttributes($attributes_value);
                $record->save(false);
            }
        }
        \yii\caching\TagDependency::invalidate(\Yii::$app->frontend_cache, SSettings::CACHE_TAG_KEY);
        return true;
    }

    public function saveAttribute($attribute, $value, $params = [], $settings = [])
    {
        $type = (isset($params['type'])) ? $params['type'] : 'text';
        switch ($type) {
            case 'img':
            case 'file':
                $file = UploadedFile::getInstance($this, $attribute);
                if ($file) {
                    $path = \Yii::getAlias("@web_frontend/uploads/settings/{$attribute}.{$file->getExtension()}");
                    if (!is_dir(pathinfo($path, PATHINFO_DIRNAME))) {
                        FileHelper::createDirectory(pathinfo($path, PATHINFO_DIRNAME), 0775, true);
                    }
                    $file->saveAs($path);
                    $value = "/uploads/settings/{$attribute}.{$file->getExtension()}";
                } else {
                    if ($value == 'deleted') {
                        $value = '';
                        $path_file = \Yii::getAlias('@web_frontend') . $value;
                        if (is_file($path_file)) {
                            @unlink($path_file);
                        }
                    } elseif (isset($settings[$attribute])) {
                        $value = $settings[$attribute]->value;
                    }
                }
        }
        return $value;
    }

    public function behaviors()
    {
        return [];
    }

    public static function find()
    {
        return \Yii::createObject(ActiveQuery::className(), [get_called_class()]);
    }

    public function addButtons()
    {
        if (count(\Yii::$app->params['languages']) > 1) {
            $langs = '';
            $default_lang = \Yii::$app->params['defaultLanguage'];
            foreach (\Yii::$app->params['languages'] as $key => $value) {
                $class = null;
                if ($key == $default_lang) {
                    $class .= 'active';
                }
                $langs .= Html::tag(
                    'li',
                    Html::a(
                        Html::tag('span', strtoupper($key)),
                        '#',
                        [
                            'class' => 'change_lang',
                            'data' => [
                                'lang' => $key
                            ]
                        ]
                    ),
                    [
                        'class' => $class,
                    ]
                );
            }
            $view = \Yii::$app->controller->view;
            $view->registerJs(<<<JS
$('.change_lang', '#pageEdit').on('click', function (e) {
    e.preventDefault();
    $(this).closest('ul').children('li').removeClass('active');
    $(this).closest('li').addClass('active');
    change_lang($(this).data('lang'));
});
function change_lang(lang) {
    $('.form-group', '#pageEdit').each(function () {
        if (typeof $(this).data('lang') != 'undefined') {
            if ($(this).data('lang') == lang) {
                $(this).show();
            } else {
                $(this).hide();
            }
        }
    });
}
JS
            );
            return '<div class="pull-right-sm"><ul class="nav nav-tabs">' . $langs . '</ul></div>';
        } else {
            return '';
        }
    }

    public function beforeValidate()
    {
        $this->postexpress_tarifs = ($this->postexpress_tarifs ? Json::encode($this->postexpress_tarifs) : []);
        $this->postexpress_tarifs_price = ($this->postexpress_tarifs_price ? Json::encode($this->postexpress_tarifs_price) : []);
        $this->delivery_kazpost_days = ($this->delivery_kazpost_days ? Json::encode($this->delivery_kazpost_days) : []);
    }
}