<?php
/**
 * Created by PhpStorm.
 * Project: kingfisher
 * User: lxShaDoWxl
 * Date: 04.01.16
 * Time: 15:27
 */
namespace backend\models;

use shadow\SSettings;
use shadow\widgets\CKEditor;
use yii\db\ActiveQuery;
use yii\helpers\ArrayHelper;
use yii\helpers\FileHelper;
use yii\web\UploadedFile;

class MailTemplate extends Settings
{
    public function FormParams()
    {
        /**
         * @var $settings Settings[]
         */
        $settings = Settings::find()->all();
        $old_settings = [];
        foreach ($settings as $item) {
            if(isset($this->data[$item->key])){
                $params_data = $this->data[$item->key];
                $old_settings[$item->key] = $item->value;
                if(isset($params_data['lang'])){
                    foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                        if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                            $old_settings[$item->key. '_' . $key_lang] = $item->{'value_' . $key_lang};
                        }
                    }
                }
            }
        }
        if ($old_settings) {
            $this->setOldAttributes($old_settings);
            $this->setAttributes($old_settings);
        }
        $groups = [];
        foreach ($this->data as $key => $val) {
            $group_key = (isset($val['group']) ? $val['group'] : 'main');
            $params = (isset($val['params']) ? $val['params'] : []);
            if (!isset($groups[$group_key])) {
                $groups[$group_key] = $this->groups[$group_key];
                $groups[$group_key]['fields'] = [];
            }
            $groups[$group_key]['fields'][$key] = $params;
            if(isset($val['lang'])){
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $groups[$group_key]['fields'][$key . '_' . $key_lang] = $params;
                    }
                }
            }
        }
        $result = [
            'form_action' => ['mail-template/save'],
//            'cancel' => ['settings/control'],
            'groups' => $groups
        ];
        return $result;
    }
    protected $groups = [
        'mail' => [
            'title' => 'Основные',
            'icon' => 'suitcase',
            'options' => [],
        ],
    ];
    /**
     * @inheritdoc
     */
    public function __get($name)
    {
        if($name=='data'){
            return $this->getData();
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    public function getData()
    {
        return [
            'mail_registration' => [
                'group' => 'mail',
                'name' => 'Подтверждение регистрации',
                'lang'=>true,
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config'=>[
                            'editorOptions'=>[
                                'enterMode'=>1
                            ]
                        ]
                    ],
                ],
            ],
        ];
    }
    public $id = null;
    /**
     * @inheritdoc
     */
    public function formName()
    {
        return 'settings'; // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributes()
    {
        $result = [];
        foreach ($this->data as $key=>$item) {
            $result[] = $key;
            if(isset($item['lang'])){
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $result[] = $key . '_' . $key_lang;
                    }
                }
            }
        }
        return $result;
    }
    protected $_attribute_labels = false;
    public function attributeLabels()
    {
        $labels = [];

        if ($this->_attribute_labels === false) {
            foreach ($this->data as $key => $val) {
                if (isset($val['name'])) {
                    $name=$val['name'];
                    $labels[$key] = $name;
                    if (isset($val['lang'])&&$val['lang']) {
                        foreach (\Yii::$app->params['languages'] as $language => $label) {
                            $labels[$key . '_' . $language] = $name . ' ' . $label;
                        }
                    }
                }
            }
            $this->_attribute_labels = $labels;
        }else{
            $labels = $this->_attribute_labels;
        }
        return $labels;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $result = [];
        foreach ($this->data as $key => $val) {
            $rule = (isset($val['rule'])) ? $val['rule'] : ([[$key], 'string']);
            $result[] = $rule;

            if(isset($val['lang'])){
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $result[] = (isset($val['rule'])) ? $val['rule'] : ([[$key.'_'.$key_lang], 'string']);;
                    }
                }
            }
        }
        return $result;
    }
    /**
     * @inheritdoc
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        /**
         * @var $settings Settings
         */
        $settings = Settings::find()->indexBy('key')->all();
        $attributes = $this->data;
        $attributes_values = [];
        foreach ($attributes as $key_attribute=>$attribute) {
            $value_attr = $this->getAttribute($key_attribute);
            $val = $this->saveAttribute($key_attribute, $value_attr,$attribute['params'],$settings);
            $attribute_val = [
                'group' => (isset($attribute['group'])) ? $attribute['group'] : 'main',
                'key' => $key_attribute,
                'value' => $val
            ];
            if(isset($attribute['lang'])){
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $name = $key_attribute.'_' . $key_lang;
                        $value_attr = $this->getAttribute($name);
                        $val = $this->saveAttribute($name, $value_attr,$attribute);
                        $attribute_val['value_' . $key_lang] = $val;
                    }
                }
            }
            $attributes_values[$key_attribute] = $attribute_val;
        }
        /**
         * @var $record Settings
         */
        foreach ($attributes_values as $key=>$attributes_value) {
            if(isset($settings[$key])){
                $record = $settings[$key];
                $update = false;
                foreach ($attributes_value as $key_name=>$value) {
                    if($record->{$key_name}!=$value){
                        $record->{$key_name}=$value;
                        $update = true;
                    }
                }
                if ($update) {
                    $record->save(false);
                }
            }else{
                $record = new Settings();
                $record->setAttributes($attributes_value);
                $record->save(false);
            }
        }
        \yii\caching\TagDependency::invalidate(\Yii::$app->frontend_cache, SSettings::CACHE_TAG_KEY);
        return true;
    }
    public function saveAttribute($attribute, $value,$params=[],$settings=[])
    {
        $type = (isset($params['type'])) ? $params['type'] : 'text';
        switch ($type) {
            case 'img':
            case 'file':
                $file = UploadedFile::getInstance($this, $attribute);
                if ($file) {
                    $path = \Yii::getAlias("@web_frontend/uploads/settings/{$attribute}.{$file->getExtension()}");
                    if (!is_dir(pathinfo($path, PATHINFO_DIRNAME))) {
                        FileHelper::createDirectory(pathinfo($path, PATHINFO_DIRNAME), 0775, true);
                    }
                    $file->saveAs($path);
                    $value = "/uploads/settings/{$attribute}.{$file->getExtension()}";
                }else{
                    if(isset($settings[$attribute])){
                        $value = $settings[$attribute]->value;
                    }
                }

        }
        return $value;
    }
    public function behaviors()
    {
        return [];
    }
    public static function find()
    {
        return \Yii::createObject(ActiveQuery::className(), [get_called_class()]);
    }
}