<?php

namespace backend\models;

use Yii;
use yii\caching\TagDependency;
use yii\helpers\Url;

/**
 * This is the model class for table "module".
 *
 * @property integer $id
 * @property string $name
 * @property string $action
 * @property string $params
 * @property string $path
 */
class Module extends \shadow\SActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'module';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'action'], 'required'],
            [['params'], 'string'],
            [['name', 'action'], 'string', 'max' => 255],
            [['path'], 'string', 'max' => 500]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Название',
            'action' => 'Action',
            'params' => 'Дополнительные параметры',
            'path' => 'ЧПУ',
        ];
    }
    public function saveClear($event)
    {
        TagDependency::invalidate(Yii::$app->frontend_cache, 'db_caching_module');
        parent::saveClear($event); // TODO: Change the autogenerated stub
    }
    public function createUrl()
    {
        return Url::to([$this->action]);
    }

    public function url()
    {
        return $this->createUrl();
    }

}
