<?php
namespace backend\modules\seo\models;

use yii;
use yii\behaviors\TimestampBehavior;
use yii\helpers\Inflector;

/**
 * This is the model class for table "s_seo_redirects".
 *
 * @property integer $id
 * @property string $old_url
 * @property string $new_url
 * @property string $type
 * @property bool $isRegex
 * @property integer $created_at
 * @property integer $updated_at
 */
class SSeoRedirects extends \shadow\SActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 's_seo_redirects';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['old_url', 'new_url'], 'trim'],
            [['old_url', 'new_url', 'type'], 'required'],
            [['old_url', 'new_url'], 'string', 'max' => 255],
            [['type'], 'string', 'max' => 3],
            ['old_url', 'unique'],
            ['isRegex', 'boolean'],
        ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'old_url' => 'Старая ссылка',
            'new_url' => 'Новая ссылка',
            'type' => 'Вид редиректа',
            'isRegex' => 'Регулярное выражение',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At'
        ];
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className()
        ];
    }
    public function FormParams()
    {
        if ($this->isNewRecord) {
            $this->loadDefaultValues(true);
        }
        $controller_name = Inflector::camel2id(Yii::$app->controller->id);
        $fields = [
            'isRegex' => [
                'type' => 'checkbox'
            ],
            'old_url' => [],
            'new_url' => [],
            'type' => [
                'type' => 'dropDownList',
                'data' => [
                    301 => 301,
                    302 => 302
                ]
            ]
        ];
        $result = [
            'form_action' => [$controller_name . '/save'],
            'cancel' => [$controller_name . '/index'],
            'groups' => [
                'main' => [
                    'title' => 'Основное',
                    'icon' => 'suitcase',
                    'options' => [],
                    'fields' => $fields
                ]
            ]
        ];
        return $result;
    }
    /**
     * @inheritdoc
     */
    public function beforeSave($insert)
    {
        $this->old_url = Yii::$app->seo->correctionUrl($this->old_url);
        $this->new_url = Yii::$app->seo->correctionUrl($this->new_url);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

}