<?php
/**
 * Created by PhpStorm.
 * Project: mymix
 * User: lxShaDoWxl
 * Date: 24.08.19
 * Time: 9:46
 */
namespace frontend\widgets;

use frontend\assets\ActiveFormAsset;
use yii\helpers\Json;

class ActiveForm extends \yii\widgets\ActiveForm
{
    /**
     * @var string the CSS class that is added to a field container when the associated attribute has validation error.
     */
    public $errorCssClass = 'error';
    /**
     * @var string the CSS class that is added to a field container when the associated attribute is successfully validated.
     */
    public $successCssClass = 'success';
    /**
     * @var string the CSS class that is added to a field container when the associated attribute is being validated.
     */
    public $validatingCssClass = 'validating';
    public $requiredCssClass = '';

    public $theme = 'instinct';
    public $events = [];
    public function run()
    {
        if ($this->enableClientScript) {
            $id = $this->options['id'];
            $options = Json::encode($this->getClientOptions());
            $attributes = Json::encode($this->attributes);
            $view = $this->getView();
            ActiveFormAsset::register($view);
            $view->registerJs("jQuery('#$id').yiiActiveForm($attributes, $options);");
            if (!\Yii::$app->request->isPjax) {
                $view->registerJs(<<<JS
$.fn.tooltipster('setDefaults', {
  position: 'bottom',
  theme:'tooltipster-{$this->theme}'
});

JS
                );
            }
            if($this->events){
                $events=<<<JS
jQuery('#$id')
JS;
                foreach ($this->events as $key=>$value) {
                    $events.=<<<JS
.on('$key',$value)
JS;

                }
                $view->registerJs($events);
            }
            $this->enableClientScript = false;
        }
        parent::run(); // TODO: Change the autogenerated stub
    }
}