<?php
/**
 * Created by PhpStorm.
 * Project: yii2-cms
 * User: lxShaDoWxl
 * Date: 29.04.15
 * Time: 13:04
 */

namespace backend\components;


use Yii;
use yii\base\Action;
use yii\web\Response;
use yii\web\UploadedFile;

class UploadAction extends Action {
    public function init()
    {
//        Yii::$app->controller->enableCsrfValidation = false;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function run()
    {
        Yii::$app->response->format = Response::FORMAT_JSON;
        $temp = Yii::$app->request->get('temp')?Yii::$app->request->get('temp'):'file';
        $result = [];
        $files = UploadedFile::getInstancesByName($temp);
        if($files){
            $tmp_path = Yii::getAlias('@backend/tmp');
            if(!is_dir($tmp_path.'/'.$temp)){
                @mkdir($tmp_path.'/'.$temp, 0775, true);
            }
            foreach ($files as $file) {
                $file_name='/'.$temp.'/'.uniqid().'.'.$file->getExtension();
                $file->saveAs($tmp_path . $file_name);
                $mask = @umask(0);
                @chmod($tmp_path . $file_name, 0644);
                @umask($mask);
                $result = [
                    'url' => $file_name,
                    'answer' => 'File transfer completed'
                ];
            }
        }
        return $result ;
    }
}