<?php
namespace backend\modules\catalog\models;

use shadow\assets\Select2Assets;
use shadow\behaviors\UploadFileBehavior;
use shadow\helpers\SArrayHelper;
use shadow\helpers\StringHelper;
use shadow\multilingual\behaviors\MultilingualBehavior;
use shadow\plugins\seo\behaviors\SSeoBehavior;
use shadow\SResizeImg;
use shadow\widgets\CKEditor;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\caching\TagDependency;
use yii\db\Expression;
use yii\db\Query;
use yii\helpers\Inflector;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\Cookie;

class Items extends BaseItems
{
    public $measure=1;
    /**
     * @inheritdoc
     */
    public function beforeValidate()
    {
        if ($this->copy) {
//            $this->detachBehavior('uploadFile');
            $b_saveRelation = $this->getBehavior('saveRelation');
            $b_uploadFile = $this->getBehavior('uploadFile');
            $b_saveRelation->copy = $this->copy;
            $b_uploadFile->copy = $this->copy;
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
        $this->saveFilters($insert);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBrand()
    {
        return $this->hasOne(Brands::className(), ['id' => 'brand_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(Category::className(), ['id' => 'cid']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategories()
    {
        return $this->hasMany(Category::className(), ['id' => 'category_id'])->via('itemsCategories');
    }
    public function setCategories($items)
    {
        if (!is_array($items)) {
            $items = [];
        }
        $event_after = $this->isNewRecord ? $this::EVENT_AFTER_INSERT : $this::EVENT_AFTER_UPDATE;
        $name = 'categories';
        $this->on($event_after, function ($event) use ($name, $items) {
            Yii::trace('start saveRelation ' . $name);
            $this->saveRelation($name, $items, $event);
        });
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAccessories()
    {
        return $this->hasMany(Items::className(), ['id' => 'item_id_accessory'])->via('itemMainAccessories');
    }
    public function setAccessories($items)
    {
        if (!is_array($items)) {
            $items = [];
        }
        $event_after = $this->isNewRecord ? $this::EVENT_AFTER_INSERT : $this::EVENT_AFTER_UPDATE;
        $name = 'accessories';
        $this->on($event_after, function ($event) use ($name, $items) {
            Yii::trace('start saveRelation ' . $name);
            $this->saveRelation($name, $items, $event);
        });
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRecommends()
    {
        return $this->hasMany(Items::className(), ['id' => 'item_rec_id'])->via('itemMainRecommends');
    }
    public function setRecommends($items)
    {
        if (!is_array($items)) {
            $items = [];
        }
        $event_after = $this->isNewRecord ? $this::EVENT_AFTER_INSERT : $this::EVENT_AFTER_UPDATE;
        $name = 'recommends';
        $this->on($event_after, function ($event) use ($name, $items) {
            Yii::trace('start saveRelation ' . $name);
            $this->saveRelation($name, $items, $event);
        });
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModifications()
    {
        return $this->hasMany(Items::className(), ['id' => 'item_mod_id'])->via('itemMainModifications');
    }
    public function setModifications($items)
    {
        if (!is_array($items)) {
            $items = [];
        }
        $event_after = $this->isNewRecord ? $this::EVENT_AFTER_INSERT : $this::EVENT_AFTER_UPDATE;
        $name = 'modifications';
        $this->on($event_after, function ($event) use ($name, $items) {
            Yii::trace('start saveRelation ' . $name);
            $this->saveModifications($items, $event);//TODO тут надо написать свою функция для сохранения модификация, универсальная не пойдёт
//            $ids_double = [];
//                if ($old_relation) {
//                    $ids_double = array_keys($old_relation);
//                }
//                $ids_double = SArrayHelper::merge($ids_double, $new_relation);
//                $ids_double = SArrayHelper::map(
//                    (new ActiveQuery($viaClass))->andWhere([$double => $ids_double])->all(),
//                    $relation->link['id'],
//                    'id',
//                    $double
//                );
        });
    }
    public function saveModifications($items, $event)
    {
        $insert_data = [];
        if ($event->name == $this::EVENT_AFTER_INSERT) {
            $old_relation = [];
        } else {
            /** @var ItemModifications[] $old_relation */
            $old_relation = $this->getItemMainModifications()->indexBy('item_mod_id')->all();
        }
        $ids_double = [];
        if ($items || $old_relation) {
            if ($old_relation) {
                $ids_double = array_keys($old_relation);
            }
            $ids_double = SArrayHelper::merge($ids_double, $items);
            $ids_double = SArrayHelper::map(
                ItemModifications::find()->andWhere(['item_main_id' => $ids_double])->all(),
                'item_mod_id',
                'id',
                'item_main_id'
            );
//            if ($old_relation) {
//                foreach ($old_relation as $key => $value) {
//                    $ids_double[$this->id][$value->item_mod_id] = $value->id;
//                }
//            }
        }
        $add_ids = [];
        foreach ($items as $key => $value) {
            if(!trim($value)){
                continue;
            }
            if (!isset($old_relation[$value])) {
                if(isset($add_ids[$value])){
                    continue;
                }
                //Основная связь этот товар > модификация
                $insert_data[] = [
                    'item_main_id' => $this->id,
                    'item_mod_id' => $value,
                ];
                if (!(isset($ids_double[$value]) && isset($ids_double[$value][$this->id]))) {
                    $ids_double[$value][$this->id] = 'new';
                    $ids_double[$this->id][$value] = 'new';
                    //Обратная связь модификация > этот товар
                    $insert_data[] = [
                        'item_main_id' => $value,
                        'item_mod_id' => $this->id,
                    ];
                    //Есть ли у выбранной модификации свои модификации
//                    if (isset($ids_double[$value])) {
//                        foreach ($ids_double[$value] as $key_d => $value_d) {
//                            if ($key_d != $this->id) {
//                                $ids_double[$key_d][$this->id] = 'new';
//                                //Добавление к этому товару модификации выбранной модификации
//                                $insert_data[] = [
//                                    'item_main_id' => $this->id,
//                                    'item_mod_id' => $key_d,
//                                ];
//                                //Добавление к модификациям выбранной модификации этот товар
//                                $insert_data[] = [
//                                    'item_main_id' => $key_d,
//                                    'item_mod_id' => $this->id,
//                                ];
//                                //Добавление к модификациям выбранной модофикации этот товар
//                                $insert_data[] = [
//                                    'item_main_id' => $key_d,
//                                    'item_mod_id' => $this->id,
//                                ];
//                            }
//                            if(isset($ids_double[$this->id])){
//                                foreach ($ids_double[$this->id] as $key_old => $value_old) {
//                                    if(isset($ids_double[$key_old])&&!isset($ids_double[$key_old][$this->id])){
//                                        $insert_data[] = [
//                                            'item_main_id' => $key_old,
//                                            'item_mod_id' => $key_d,
//                                        ];
//                                        $insert_data[] = [
//                                            'item_main_id' => $key_d,
//                                            'item_mod_id' => $key_old,
//                                        ];
//                                    }
//                                }
//                            }
//                        }
//                    }
                }
            } else {
                unset($old_relation[$value]);
                $ids_double[$this->id][$value] = 'old';
            }
            $add_ids[$value] = $value;
        }
        if (isset($ids_double[$this->id]) && $ids_double[$this->id]) {
            foreach ($ids_double[$this->id] as $key => $value) {
                foreach ($ids_double[$this->id] as $key_this => $value_this) {
                    if (!isset($ids_double[$key][$key_this]) && $key != $key_this) {
                        $ids_double[$key][$key_this] = 'new';
                        $ids_double[$key_this][$key] = 'new';
                        $insert_data[] = [
                            'item_main_id' => $key,
                            'item_mod_id' => $key_this,
                        ];
                        $insert_data[] = [
                            'item_main_id' => $key_this,
                            'item_mod_id' => $key,
                        ];
//                $this->addModifications($key_this, $insert_data, $ids_double);
                    }
                }
                $this->addModifications($key, $insert_data, $ids_double);
            }
        }
        if ($old_relation) {
            $delete_data = [];
            foreach ($old_relation as $key => $value) {
                $delete_data[] = $key;
//                if (isset($ids_double[$key])) {
//                    $delete_data = array_merge($delete_data, $ids_double[$key]);
//                    $delete_data[] = $ids_double[$key][$this->id];
//                    foreach ($ids_double[$key] as $key_d => $value_d) {
//                        if (isset($ids_double[$key_d]) && isset($ids_double[$key_d][$this->id]) && is_numeric($ids_double[$key_d][$this->id])) {
//                            $delete_data[] = $ids_double[$key_d][$this->id];
//                        }
//                    }
//                }
            }
            if ($delete_data) {
                \Yii::$app->db->createCommand()->delete(ItemModifications::tableName(),
                    [
                        'OR',
                        ['item_main_id' => $delete_data],
                        ['item_mod_id' => $delete_data]
                    ]
                )->execute();
            }
        }
        if ($insert_data) {
            \Yii::$app->db->createCommand()->batchInsert(ItemModifications::tableName(),
                [
                    'item_main_id',
                    'item_mod_id'
                ],
                $insert_data)->execute();
//            $old_relation = $this->getItemMainModifications()->indexBy('item_mod_id')->all();
//            if ($old_relation) {
//                $ids_double = array_keys($old_relation);
//                $ids_double = SArrayHelper::map(
//                    ItemModifications::find()->andWhere(['item_main_id' => $ids_double])->all(),
//                    'item_mod_id',
//                    'id',
//                    'item_main_id'
//                );
//                foreach ($ids_double as $key => $value) {
//
//                }
//            }
        }
    }
    private function addModifications($key, &$insert_data, &$ids_double)
    {
        foreach ($ids_double[$key] as $key_two => $value_two) {
            if (!isset($ids_double[$this->id][$key_two])) {
                if ($key_two != $this->id) {
                    $ids_double[$this->id][$key_two] = 'new';
                    $ids_double[$key_two][$this->id] = 'new';
                    $insert_data[] = [
                        'item_main_id' => $this->id,
                        'item_mod_id' => $key_two,
                    ];
                    $insert_data[] = [
                        'item_main_id' => $key_two,
                        'item_mod_id' => $this->id,
                    ];
                    $this->addModifications($key_two, $insert_data, $ids_double);
                }
            }
        }
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        $result = [
            TimestampBehavior::className(),
            'uploadFile' => [
                'class' => UploadFileBehavior::className(),
                'attributes' => [
                    'img_list',
                    'file',
                ]
            ],
            'saveRelation' => [
                'class' => '\shadow\behaviors\SaveRelationBehavior',
                'relations' => [
                    ItemImg::className() => [
                        'type' => 'img',
                        'attribute' => 'item_id',
                        'extra_attributes' => [
                            'sort',
                            'name'
                        ]
                    ],
//                    ItemOptionsValue::className() => [
//                        'type' => 'MANY_MANY',
//                        'attribute' => 'item_id',
//                        'attribute_main' => 'option_value_id',
//                        'attribute_group' => 'option_id',
//                        'many_many' => [
//                            'model' => OptionsValue::className(),
//                            'attributes' => function ($id_option, $value_select) {
//                                return [
//                                    'option_id' => $id_option,
//                                    'value' => $value_select
//                                ];
//                            }
//                        ],
//                        'attributes' => ['option_id', 'option_value_id'],
////                        'multiple'=>[
////                            'field_group'=>'option_id',
////                            'id'=>'option_id',
////                            'field_value'=>function ($element) {
////                                return $element;
////                            }
////                        ],
//                    ]
                ],
            ],
        ];
        if (Yii::$app->function_system->enable_multi_lang()) {
            $result['ml'] = [
                'class' => MultilingualBehavior::className(),
                'languages' => Yii::$app->params['languages'],
                'defaultLanguage' => 'ru',
                'langForeignKey' => 'owner_id',
                'tableName' => "{{%items_lang}}",
                'attributes' => [
                    'name',
                    'body',
                    'body_small',
                ]
            ];
        }
        if (SSeoBehavior::enableSeoEdit()) {
            $result['seo'] = [
                'class' => SSeoBehavior::className(),
                'nameTranslate' => 'name',
                'controller' => 'site',
                'action' => 'item',
                'parentRelation' => 'c',
            ];
        }
        return $result;
    }
    public static $data_status = [
        0 => 'Под заказ',
        1 => 'В наличие'
    ];
    public static $data_recommend_type = [
        0 => 'Выкл',
        1 => 'Вкл',
        2 => 'Авто',
    ];
    public $copy = 0;
    public function FormParams()
    {
        /**
         * @var ItemImg[] $relation_imgs
         */
        $imgs = $accessories = $modifications=$recommends = [];
        $cats = Category::find()->where('parent_id is NULL')->all();
        $selects = (new Category())->SelectViewCat($cats, 0, [], ['cats' => ['disabled' => true]]);
        if ($this->isNewRecord) {
            $this->loadDefaultValues(true);
        } else {
            $relation_imgs = ItemImg::find()->where(array('item_id' => $this->id))->orderBy(['sort' => SORT_ASC])->all();
            foreach ($relation_imgs as $value) {
                $imgs[] = [
                    'name' => StringHelper::basename($value->url),
                    'size' => 0,
//                    'type' => mime_content_type(Yii::getAlias('@frontend'). $value->url),
                    'url' => $value->url,
                    'title' => $value->name,
                    'sort' => $value->sort,
                    'id' => $value->id
                ];
            }
        }
        if ($this->isNewRecord && ($copy_id = \Yii::$app->request->get('copy'))) {
            $copy_item = Items::findOne($copy_id);
            if ($copy_item) {
                $this->setAttributes($copy_item->attributes);
                $this->populateRelation('categories', $copy_item->categories);
                $this->populateRelation('accessories', $copy_item->accessories);
                $this->populateRelation('modifications', $copy_item->modifications);
                $accessories = $copy_item->getAccessories()->indexBy('id')->select(['name', 'id'])->column();
                $this->copy = $copy_item->id;
                $relation_imgs = ItemImg::find()->where(array('item_id' => $copy_item->id))->orderBy(['sort' => SORT_ASC])->all();
                foreach ($relation_imgs as $value) {
                    $imgs[] = [
                        'name' => StringHelper::basename($value->url),
                        'size' => 0,
//                    'type' => mime_content_type(Yii::getAlias('@frontend'). $value->url),
                        'url' => $value->url,
                        'title' => $value->name,
                        'sort' => $value->sort,
                        'id' => $value->id
                    ];
                }
            }
        } else {
            if (!$this->isNewRecord) {
                $accessories = $this->getAccessories()->indexBy('id')->select(['name', 'id'])->column();
                $modifications = $this->getModifications()->indexBy('id')->select(['name', 'id'])->column();
                $recommends = $this->getRecommends()->indexBy('id')->select(['name', 'id'])->column();
            } else {
//                $accessories = Items::find()->indexBy('id')->select(['name', 'id'])->limit()->column();
            }
        }
        $controller_name = Inflector::camel2id(Yii::$app->controller->id);
        $fields = [
            'copy' => [
                'field_options' => [
                    'options' => [
                        'class' => 'hidden'
                    ]
                ],
                'type' => 'hidden'
            ],
            'isVisible' => [
                'type' => 'checkbox'
            ],
            'isDay' => [
                'type' => 'checkbox'
            ],
            'isSale' => [
                'type' => 'checkbox'
            ],
            'isNew' => [
                'type' => 'checkbox'
            ],
            'isHit' => [
                'type' => 'checkbox'
            ],
            'googleFid' => [
                'type' => 'checkbox',
				'title'=>'Отображать в Google Fid'
            ],
            'cid' => [
                'type' => 'dropDownList',
                'data' => isset($selects['data']) ? $selects['data'] : [],
                'params' => [
                    'options' => isset($selects['options']) ? $selects['options'] : [],
                ]
            ],
            'categories' => [
                'title' => 'Доп. категории',
                'type' => 'dropDownList',
                'data' => isset($selects['data']) ? $selects['data'] : [],
                'params' => [
                    'options' => isset($selects['options']) ? $selects['options'] : [],
                    'multiple' => true,
                ]
            ],
            'brand_id' => [
                'type' => 'dropDownList',
                'relation' => [
                    'class' => Brands::className()
                ]
            ],
            'status' => [
                'type' => 'dropDownList',
                'data' => self::$data_status
            ],
            'name' => [],
            'model' => [],
            'vendor_code' => [],
            'isPriceFrom' => [
                'type' => 'checkbox'
            ],
            'price' => [],
            'old_price' => [],
            'discount' => [],
            'dealer_price' => [],
            'rates_id' => [
                'type' => 'dropDownList',
                'relation' => [
                    'class' => Rates::className()
                ]
            ],
            'exchange_price' => [],
            'img_list' => [
                'type' => 'img',
                'params' => [
                    'deleted' => false
                ]
            ],
            'popularity' => [],
			'tops' => [],
            'weight' => [],
            'warranty' => [],
            'video' => [],
            'file' => [
                'type' => 'file',
                'params' => [
                    'deleted' => true
                ]
            ],
            'isDeleted' => [
                'type' => 'checkbox'
            ],
//            'rate' => [],
//            'count_reviews' => []
        ];
		
        $fields_content = [
            'body_small' => [
                'type' => 'textArea',
            ],
            'body' => [
                'type' => 'textArea',
                'widget' => [
                    'class' => CKEditor::className(),
                    'config' => [
                        'editorOptions' => [
                            'enterMode' => 0
                        ]
                    ]
                ]
            ],
            'feature' => [
                'type' => 'textArea',
                'widget' => [
                    'class' => CKEditor::className(),
                    'config' => [
                        'editorOptions' => [
                            'enterMode' => 0
                        ]
                    ]
                ]
            ],
            'package' => [
                'type' => 'textArea',
                'widget' => [
                    'class' => CKEditor::className(),
                    'config' => [
                        'editorOptions' => [
                            'enterMode' => 0
                        ]
                    ]
                ]
            ],
            'body_list' => [
                'type' => 'textArea',
                'widget' => [
                    'class' => CKEditor::className(),
                    'config' => [
                        'editorOptions' => [
                            'enterMode' => 0
                        ]
                    ]
                ]
            ],
        ];
        $result = [
            'form_action' => [$controller_name . '/save'],
            'cancel' => Yii::$app->controller->url['back'],
            'groups' => [
                'main' => [
                    'title' => 'Основное',
                    'icon' => 'suitcase',
                    'options' => [],
                    'fields' => $fields
                ],
                'content' => [
                    'title' => 'Контент',
                    'icon' => 'file-text',
                    'options' => [],
                    'fields' => $fields_content
                ],
                'imgs' => [
                    'title' => 'Изображения',
                    'icon' => 'picture-o',
                    'options' => [],
                    'fields' => [
                        'js_files' => [
                            'files' => [
//                                'title'=>'Js Файлы',
                                'name' => 'itemImg',
                                'filters' => [
                                    'imageFilter' => true,
                                ],
                                'isSort' => true,
                                'isName' => true,
                                'value' => $imgs
                            ]
                        ],
                    ]
                ],
                'values' => [
                    'title' => 'Характеристики',
                    'icon' => 'th-list',
                    'options' => [],
                    'render' => [
                        'view' => 'filters'
                    ]
                ],
//                'modifications-tab' => [
//                    'title' => 'Мод-кации',
//                    'icon' => 'th-list',
//                    'options' => [],
//                    'relation' => [
//                        'class' => ItemModifications::className(),
//                        'remote_data'=>[
//                            'url'=>Json::encode(Url::to(['items/list']))
//                        ],
//                        'name'=>$this->formName().'[modifications]',
//                        'width' => 12,
//                        'type'=>'MANY_MANY',
//                        'items'=>$this->modifications,
//                        'attributes'=>[
//                            'id'=>[
//                                'label'=>'Товар',
//                                'type'=>'dropDownList',
//                                'data'=>$modifications
//                            ]
//                        ]
//                    ]
//                ],
//                'accessories-tab' => [
//                    'title' => 'Прин-сти',
//                    'icon' => 'th-list',
//                    'options' => [],
//                    'relation' => [
//                        'class' => ItemAccessory::className(),
//                        'remote_data'=>[
//                            'url'=>Json::encode(Url::to(['items/list']))
//                        ],
//                        'name'=>$this->formName().'[accessories]',
//                        'width' => 12,
//                        'type'=>'MANY_MANY',
//                        'items'=>$this->accessories,
//                        'attributes'=>[
//                            'id'=>[
//                                'label'=>'Товар',
//                                'type'=>'dropDownList',
//                                'data'=>$accessories
//                            ]
//                        ]
//                    ]
//                ],
                'recommends' => [
                    'title' => 'Рекомендуемые',
                    'icon' => 'th-list',
                    'options' => [],
                    'fields' => [
                        'recommend_type' => [
                            'type' => 'dropDownList',
                            'data' => self::$data_recommend_type
                        ],
                        'recommends' => [
                            'title' => 'Товары',
                            'type' => 'dropDownList',
                            'data' => $recommends,
                            'field_options' => [
                                'options' => [
                                    'class' => 'hidden'
                                ]
                            ],
                            'params' => [
                                'multiple' => true,
                            ]
                        ],
                    ]
                ],
            ]
        ];
        if ($this->getBehavior('ml')) {
            $this->ParamsLang($result, $fields);
            $this->ParamsLang($result, $fields_content);
        }
        $cat_id = Yii::$app->request->get('cat');
        if ($cat_id && $this->isNewRecord) {
            $this->cid = $cat_id;
        }
        if ($cat_id) {
            if ($filters = $this->filtersItem($cat_id)) {
                $result['groups']['values']['render']['data'] = [
                    'filters' => $filters,
                    'item' => $this
                ];
            }
        }
        if (!$this->isNewRecord) {
            if ($filters = $this->filtersItem(false, $this->id)) {
                $result['groups']['values']['render']['data'] = [
                    'filters' => $filters,
                    'item' => $this
                ];
            }
        }
        if ($this->copy) {
            if (isset($copy_item) && ($filters = $this->filtersItem(false, $copy_item->id))) {
                $result['groups']['values']['render']['data'] = [
                    'filters' => $filters,
                    'item' => $this
                ];
            }
        }
        $form_name = strtolower($this->formName());
        $view = Yii::$app->view;
        Select2Assets::register($view);
        $view->registerJs(<<<JS
$('#{$form_name}-categories').select2({
    //width: '250px',
    language: 'ru'
});
//$('#{$form_name}-recommends').select2({
//    width: '100%',
//    language: 'ru'
//});
if ($('#{$form_name}-recommend_type').val() == 1) {
    $('.field-{$form_name}-recommends').removeClass('hidden');
}
$('#{$form_name}-recommend_type').on('change', function (e) {
    if ($(this).val() == 1) {
        $('.field-{$form_name}-recommends').removeClass('hidden');
    } else {
        $('.field-{$form_name}-recommends').addClass('hidden');
    }
})
JS
        );
        //region Принадлежности
        $url = Json::encode(Url::to(['items/list']));
        $view->registerCss(".select2-result-repository { padding-top: 4px; padding-bottom: 3px; }
.select2-result-repository__avatar { float: left; width: 60px; margin-right: 10px; }
.select2-result-repository__avatar img { width: 100%; height: auto; border-radius: 2px; }
.select2-result-repository__meta { margin-left: 70px; }
.select2-result-repository__title { color: black; font-weight: bold; word-wrap: break-word; line-height: 1.1; margin-bottom: 4px; }
.select2-result-repository__description { font-size: 13px; color: #777; margin-top: 4px; }
.select2-results__option--highlighted .select2-result-repository__title { color: white; }
.select2-results__option--highlighted .select2-result-repository__forks, .select2-results__option--highlighted .select2-result-repository__stargazers, .select2-results__option--highlighted .select2-result-repository__description, .select2-results__option--highlighted .select2-result-repository__watchers { color: #c6dcef; }
.select2-container .select2-selection--multiple .select2-selection__rendered {
    text-overflow: initial;
    white-space: initial;
}"
        );
        $id_json=Json::encode($this->id);
        $view->registerJs(<<<JS
$('#{$form_name}-accessories,#{$form_name}-recommends').select2({
        width: '100%',
        language: 'ru',
        ajax: {
            url: {$url},
            dataType: 'json',
            //delay: 250,
            data: function (params) {
                return {
                    q: params.term, // search term
                    page: params.page,
                    id:{$id_json}
                };
            },
            processResults: function (data, params) {
                // parse the results into the format expected by Select2
                // since we are using custom formatting functions we do not need to
                // alter the remote JSON data, except to indicate that infinite
                // scrolling can be used
                params.page = params.page || 1;
                return {
                    results: data.items,
                    pagination: {
                        more: (params.page * 30) < data.total_count
                    }
                };
            },
            cache: true
        },
        escapeMarkup: function (markup) {
            return markup;
        },
        //minimumInputLength: 0,
        templateResult: formatRepo,
        templateSelection: formatRepoSelection
    });
$('#{$form_name}-modifications').select2({
        width: '100%',
        language: 'ru',
        ajax: {
            url: {$url},
            dataType: 'json',
            //delay: 250,
            data: function (params) {
                return {
                    q: params.term, // search term
                    page: params.page,
                    id:{$id_json}
                };
            },
            processResults: function (data, params) {
                // parse the results into the format expected by Select2
                // since we are using custom formatting functions we do not need to
                // alter the remote JSON data, except to indicate that infinite
                // scrolling can be used
                params.page = params.page || 1;
                return {
                    results: data.items,
                    pagination: {
                        more: (params.page * 30) < data.total_count
                    }
                };
            },
            cache: true
        },
        escapeMarkup: function (markup) {
            return markup;
        },
        //minimumInputLength: 0,
        templateResult: formatRepo,
        templateSelection: formatRepoSelection
    });

function formatRepo(item) {
    if (item.loading) return item.text;
    return "<div class='select2-result-repository clearfix'>" +
        "<div class='select2-result-repository__avatar'><img src='" + item.img + "' /></div>" +
        "<div class='select2-result-repository__meta'>" +
        "<div class='select2-result-repository__title'>" + item.name + "</div>"+
        "<div class='select2-result-repository__description'>Артикул: " + item.vendor_code + "<br/>ID:"+item.id+"</div>"+
        "</div></div>";
}

function formatRepoSelection(item) {
    return item.name || item.text;
}
JS
        );
        //endregion
        return $result;
    }
    public function filtersItem($id, $item_id = false, $not_null = false)
    {
        $result = array();
        $q = new Query();
        $select = [
            'cat_name' => '`t`.name',
            'id_link' => '`t`.id',
            '`options`.`id`',
            '`options`.`name`',
            '`options`.`type`',
            '`options`.`measure`',
            'option_id' => 'options_value.option_id',
            '`options_value`.`value`',
            'item_option_value' => 'item_options_value.option_value_id',
            'item_option_value_min' => 'item_options_value.value',
            'item_option_value_max' => 'item_options_value.max_value',
            'option_value_id' => '`options_value`.`id`',
        ];
        if ($not_null) {
            $q->andWhere('`options`.`id` is NOT NULL AND `item_options_value`.`value` is NOT NULL AND `item_options_value`.`value`<>""');
        } else {
            $q->andWhere('`options`.`id` is NOT NULL');
        }
        if ($id && !$item_id) {
            $q->join('LEFT JOIN', 'options_category', '`options_category`.`cid` = `t`.`id`');
            $q->join('LEFT JOIN', 'options', '`options`.`id` = `options_category`.`option_id`');
            $q->join('LEFT JOIN', 'options_value', '`options`.`id` = `options_value`.`option_id`');
            $q->join('LEFT JOIN', 'item_options_value', '`item_options_value`.`option_id` = `options`.`id`');
            $q->andWhere(['`t`.id' => $id]);
            $table = '`category` `t`';
            $select['item_option_value'] = new Expression('""');
        } else {
            $q->params = [':id' => $item_id];
            $q->join('LEFT JOIN', 'options_category', '`options_category`.`option_id` = `options`.`id`');
            $q->join('LEFT JOIN', '`category` `t`', '`t`.`id` = `options_category`.`cid`');
            $q->join('LEFT JOIN', 'item_options_value', '`item_options_value`.`option_id` = `options`.`id` AND `item_options_value`.`item_id` = :id');
            $q->join('LEFT JOIN', 'options_value', '`item_options_value`.`option_value_id` = `options_value`.`id`  OR  `options_value`.`option_id`=`options`.id');
            $q->andWhere(new Expression('IF(`item_options_value`.`item_id` = :id,1,IF(`t`.`id` is NOT NULL,1,0))=1'));
            $q->andWhere(
                [
                    'OR',
                    ['`t`.id' => $this->cid],
                    '`t`.`id` is NULL'
                ]
            );
            $table = 'options';
        }
        $q->select($select);
        $rows = $q->from($table)->all();
        if ($rows) {
            foreach ($rows as $row) {
                if (!$row['id_link']) {
                    $row['id_link'] = 'all';
                    $result[$row['id_link']]['title'] = 'Фильтры без категории';
                } else {
                    $result[$row['id_link']]['title'] = 'Фильтры категории "' . $row['cat_name'] . '"';
                }
                if (!isset($result[$row['id_link']]['options'][$row['id']])) {
                    $result[$row['id_link']]['options'][$row['id']] = $row;
                    $result[$row['id_link']]['options'][$row['id']]['values'] = [];
                    $result[$row['id_link']]['options'][$row['id']]['value'] = [];
                }
                if ($row['type'] == 'multi_select' || $row['type'] == 'one_select') {
                    if ($row['option_id'] == $row['id']) {
                        if (!in_array($row['value'], $result[$row['id_link']]['options'][$row['id']]['values'])) {
                            $result[$row['id_link']]['options'][$row['id']]['values'][$row['option_value_id']] = $row['value'];
                        }
                        if ($row['item_option_value'] && !in_array($row['item_option_value'], $result[$row['id_link']]['options'][$row['id']]['value'])) {
                            $result[$row['id_link']]['options'][$row['id']]['value'][] = $row['item_option_value'];
                        }
                    }
                } else {
                    $result[$row['id_link']]['options'][$row['id']]['value']['value'] = $row['item_option_value_min'];
                    $result[$row['id_link']]['options'][$row['id']]['value']['max_value'] = $row['item_option_value_max'];
                }
            }
        }
        return $result;
    }
    public function saveFilters($insert)
    {
        $data = \Yii::$app->request->post('itemOptionsValue', []);
        $old_items = $items = [];
        if (!$insert) {
            $old_items = ItemOptionsValue::find()->where(['item_id' => $this->id])->indexBy('id')->all();
            $items = SArrayHelper::map(
                $old_items,
                function ($element) {
                    return ($element->option_value_id ? $element->option_value_id : 0);
                },
                function ($element) {
                    return $element;
                },
                'option_id'
            );
        }
        $sql = '';
        $q_builder = \Yii::$app->db->queryBuilder;
        $sql_params = [];
        if ($data) {
            /** @var Options[] $options */
            $options = Options::find()->andWhere(['id' => array_keys($data)])->indexBy('id')->all();
            foreach ($data as $key => $value) {
                $option = $options[$key];
                if ($option->type == 'multi_select') {
                    if (isset($items[$option->id])) {
                        foreach ($value['option_value_id'] as $option_value_id) {
                            $id_select = (int)$option_value_id;
                            if ($option_value_id && !is_numeric($option_value_id)) {
                                $record_option_value = new OptionsValue();
                                $record_option_value->option_id = $option->id;
                                $record_option_value->value = $option_value_id;
                                if ($record_option_value->save(false)) {
                                    $id_select = $record_option_value->id;
                                } else {
                                    continue;
                                }
                            }
                            if (isset($items[$option->id][$id_select])) {
                                unset($old_items[$items[$option->id][$id_select]->id]);
                            } else {
                                $sql .= $q_builder->insert(
                                        '{{%item_options_value}}',
                                        [
                                            'item_id' => $this->id,
                                            'option_id' => $option->id,
                                            'option_value_id' => $id_select,
                                        ],
                                        $sql_params
                                    ) . ";\n";
                            }
                        }
                    } else {
                        foreach ($value['option_value_id'] as $option_value_id) {
                            $id_select = (int)$option_value_id;
                            if ($option_value_id && !is_numeric($option_value_id)) {
                                $record_option_value = new OptionsValue();
                                $record_option_value->option_id = $option->id;
                                $record_option_value->value = $option_value_id;
                                if ($record_option_value->save(false)) {
                                    $id_select = $record_option_value->id;
                                } else {
                                    continue;
                                }
                            }
                            $sql .= $q_builder->insert(
                                    '{{%item_options_value}}',
                                    [
                                        'item_id' => $this->id,
                                        'option_id' => $option->id,
                                        'option_value_id' => $id_select,
                                    ],
                                    $sql_params
                                ) . ";\n";
                        }
                    }
                } elseif ($option->type == 'one_select') {
                    $value['option_value_id'] = trim($value['option_value_id']);
                    if (!$value['option_value_id']) {
                        continue;
                    }
                    $id_select = (int)$value['option_value_id'];
                    if ($value['option_value_id'] && !is_numeric($value['option_value_id'])) {
                        $record_option_value = new OptionsValue();
                        $record_option_value->option_id = $option->id;
                        $record_option_value->value = $value['option_value_id'];
                        if ($record_option_value->save(false)) {
                            $id_select = $record_option_value->id;
                        } else {
                            continue;
                        }
                    }
                    if (isset($items[$option->id])) {
                        $id_old = key($items[$option->id]);
                        if ($id_old != $id_select) {
                            if (!$id_select) {
                                continue;
                            }
                            unset($old_items[$items[$option->id][$id_old]->id]);
                            $sql .= $q_builder->update(
                                    '{{%item_options_value}}',
                                    [
                                        'option_value_id' => $id_select,
                                    ],
                                    [
                                        'id' => $items[$option->id][$id_old]->id
                                    ],
                                    $sql_params
                                ) . ";\n";
                        } else {
                            unset($old_items[$items[$option->id][$id_select]->id]);
                        }
                    } else {
                        $sql .= $q_builder->insert(
                                '{{%item_options_value}}',
                                [
                                    'item_id' => $this->id,
                                    'option_id' => $option->id,
                                    'option_value_id' => $id_select,
                                ],
                                $sql_params
                            ) . ";\n";
                    }
                } elseif ($option->type == 'range') {
                    $value['value'] = preg_replace('/[^0-9.,]*/', '', str_replace(',', '.', $value['value']));
                    $value['max_value'] = preg_replace('/[^0-9.,]*/', '', str_replace(',', '.', $value['max_value']));
                    if (isset($items[$option->id])) {
                        if (
                            $items[$option->id][0]->value != $value['value']
                            ||
                            $items[$option->id][0]->max_value != $value['max_value']
                        ) {
                            if ($value['max_value'] == '' && $value['value'] == '') {
                                continue;
                            }
                            unset($old_items[$items[$option->id][0]->id]);
                            $sql .= $q_builder->update(
                                    '{{%item_options_value}}',
                                    [
                                        'value' => $value['value'],
                                        'max_value' => $value['max_value']
                                    ],
                                    [
                                        'id' => $items[$option->id][0]->id
                                    ],
                                    $sql_params
                                ) . ";\n";
                        } else {
                            unset($old_items[$items[$option->id][0]->id]);
                        }
                    }else{
                        $sql .= $q_builder->insert(
                                '{{%item_options_value}}',
                                [
                                    'item_id' => $this->id,
                                    'option_id' => $option->id,
                                    'option_value_id' => null,
                                    'value' => $value['value'],
                                    'max_value' => $value['max_value']
                                ],
                                $sql_params
                            ) . ";\n";
                    }
                } elseif ($option->type == 'number') {
                    $value['value'] = preg_replace('/[^0-9.,]*/', '', str_replace(',', '.', $value['value']));
                    if (isset($items[$option->id])) {
                        if ($items[$option->id][0]->value != $value['value']) {
                            if ($value['value'] != '') {
                                unset($old_items[$items[$option->id][0]->id]);
                                $sql .= $q_builder->update(
                                        '{{%item_options_value}}',
                                        [
                                            'value' => $value['value']
                                        ],
                                        [
                                            'id' => $items[$option->id][0]->id
                                        ],
                                        $sql_params
                                    ) . ";\n";
                            }
                        } else {
                            unset($old_items[$items[$option->id][0]->id]);
                        }
                    } else {
                        $sql .= $q_builder->insert(
                                '{{%item_options_value}}',
                                [
                                    'item_id' => $this->id,
                                    'option_id' => $option->id,
                                    'option_value_id' => null,
                                    'value' => $value['value']
                                ],
                                $sql_params
                            ) . ";\n";
                    }
                } elseif ($option->type == 'value') {
                    $value['value'] = trim($value['value']);
                    if (isset($items[$option->id])) {
                        if ($items[$option->id][0]->value != $value['value']) {
                            if ($value['value'] != '') {
                                unset($old_items[$items[$option->id][0]->id]);
                                $sql .= $q_builder->update(
                                        '{{%item_options_value}}',
                                        [
                                            'value' => $value['value']
                                        ],
                                        [
                                            'id' => $items[$option->id][0]->id
                                        ],
                                        $sql_params
                                    ) . ";\n";
                            }
                        } else {
                            unset($old_items[$items[$option->id][0]->id]);
                        }
                    } else {
                        $sql .= $q_builder->insert(
                                '{{%item_options_value}}',
                                [
                                    'item_id' => $this->id,
                                    'option_id' => $option->id,
                                    'option_value_id' => null,
                                    'value' => $value['value']
                                ],
                                $sql_params
                            ) . ";\n";
                    }
                }
            }
        }
        if ($old_items) {
            $deleted = array_keys($old_items);
            if ($deleted) {
                Yii::$app->db->createCommand()->delete('{{%item_options_value}}', ['id' => $deleted])->execute();
            }
        }
        if ($sql) {
            \Yii::$app->db->createCommand($sql, $sql_params)->execute();
        }
    }
    use SResizeImg;
    public $watermark_path = '/uploads/watemark_toolsmart-8.png';

    /**
     * @param bool $resize
     * @param string|array $size_type
     * @param bool $array
     * @return string|array
     */
    public function img($resize = false, $size_type = 'mini', $array = false)
    {
        if (!$array) {
            if ($this->img_list) {
                if ($resize && isset(ItemImg::$_size_img_a[$size_type])) {
                    $result = $this->resizeImg(ItemImg::$_size_img_a[$size_type], 'img_list');
                } else {
                    $result = $this->img_list;
                }
            } else {
                if (isset($this->itemImgs[0]->url)) {
                    if ($resize) {
                        $result = $this->itemImgs[0]->resizeImg($size_type);
                    } else {
                        $result = $this->itemImgs[0]->url;
                    }
                } else {
                    $result = '/uploads/no_photo.png';
                }
            }
            if (!$result) {
                $result = '/uploads/no_photo.png';
            }
            if ($result != '/uploads/no_photo.png' && !is_file(Yii::getAlias('@frontend/web') . $result)) {
                $result = '/uploads/no_photo.png';
            }
        } else {
            $result = [];
            if ($this->itemImgs) {
                $result = array();
                foreach ($this->itemImgs as $img) {
                    if ($resize) {
                        if (is_array($size_type)) {
                            $img_size = [];
                            foreach ($size_type as $value) {
                                if ($img_resize = $img->resizeImg($value)) {
                                    $img_size[$value] = $img_resize;
                                }else{
                                    $img_size[$value] = '';
                                }
                            }
                            $img_size['title'] = $img->name;
                            $result[] = $img_size;
                        } else {
                            if ($img_resize = $img->resizeImg($size_type)) {
                                $result[] = $img_resize;
                            }
                        }
                    } else {
                        if (is_file(Yii::getAlias('@frontend/web') . $img->url)) {
                            $result[] = $img->url;
                        }
                    }
                }
            } else {
                if ($this->img_list) {
                    if ($resize) {
                        if (is_array($size_type)) {
                            $img_size = [];
                            foreach ($size_type as $value) {
                                if (!isset(ItemImg::$_size_img_a[$value])) {
                                    if (is_file(Yii::getAlias('@frontend/web') . $this->img_list)) {
                                        $img_size[$value] = $this->img_list;
                                    }else{
                                        $img_size[$value] = null;
                                    }
                                    continue;
                                }
                                if ($img_resize = $this->resizeImg(ItemImg::$_size_img_a[$value], 'img_list')) {
                                    $img_size[$value] = $img_resize;
                                }
                            }
                            $img_size['title'] = $this->name;
                            $result[] = $img_size;
                        } else {
                            if (isset(ItemImg::$_size_img_a[$size_type]) && ($img_resize = $this->resizeImg(ItemImg::$_size_img_a[$size_type], 'img_list'))) {
                                $result[] = $img_resize;
                            }
                        }
                    } else {
                        if (is_file(Yii::getAlias('@frontend/web') . $this->img_list)) {
                            $result[] = $this->img_list;
                        }
                    }
                }
            }
            if (!$result) {
                $result[] = '/uploads/no_photo.png';
            }
        }
        return $result;
    }

    /**
     * @param $size_type - массив/строка размеров, которые должны быть у созданных копий
     * @return array
     */
    public function seoImg($size_type){
        $result = [];
        if ($this->itemImgs) {
            foreach ($this->itemImgs as $key=>$img) {
                if (is_array($size_type)) {
                    $img_size = [];
                    foreach ($size_type as $value) {
                        if ($img_resize = $img->resizeImg($value)) {
                            $img_size[$value] = $img_resize;
                        }else{
                            $img_size[$value] = '';
                        }
                    }
                    $result[] = $img_size;
                } else {
                    if ($img_resize = $img->resizeImg($size_type)) {
                        $result[] = $img_resize;
                    }
                }
            }

        }elseif ($this->img_list) {
            if (is_array($size_type)) {
                $img_size = [];
                foreach ($size_type as $value) {
                    if (!isset(ItemImg::$_size_img_a[$value])) {
                        if (is_file(Yii::getAlias('@frontend/web') . $this->img_list)) {
                            $img_size[$value] = $this->img_list;
                        }else{
                            $img_size[$value] = null;
                        }
                        continue;
                    }
                    if ($img_resize = $this->resizeImg(ItemImg::$_size_img_a[$value], 'img_list')) {
                        $img_size[$value] = $img_resize;
                    }
                }
                $result[] = $img_size;
            } else {
                if (isset(ItemImg::$_size_img_a[$size_type]) && ($img_resize = $this->resizeImg(ItemImg::$_size_img_a[$size_type], 'img_list'))) {
                    $result[] = $img_resize;
                }
            }
        }
        return $result;
    }

    public function url($scheme = false)
    {
        $params = ['site/item', 'id' => $this->id];
        return Url::to($params, $scheme);
    }
    public static function parseCode($hash)
    {
        $filter_json = base64_decode($hash);
        $filters = json_decode($filter_json, true);
        return $filters;
    }
    public static function parseEncode($filter_json)
    {
        $filters = json_encode($filter_json, true);
        $filter_json = base64_encode($filters);
        return $filter_json;
    }

    public function add_views()
    {
        $catalog_views = \Yii::$app->request->cookies->getValue('catalog');
        $update = true;
        if ($catalog_views) {
            $catalog_views = Json::decode($catalog_views);
            if (!isset($catalog_views[$this->id])) {
                $catalog_views[$this->id] = time();
                $catalog_views = Json::encode($catalog_views);
            } else {
                $update = false;
            }
        } else {
            $catalog_views = [];
            $catalog_views[$this->id] = time();
            $catalog_views = Json::encode($catalog_views);
        }
        if ($update) {
            Yii::$app->db->createCommand()->update(
                $this->tableName(),
                [
                    'popularity' => new Expression('`popularity`+1')
                ],
                [
                    'id' => $this->id
                ]
            )->execute();
            $cookie = new Cookie([
                'name' => 'catalog',
                'value' => $catalog_views,
                'expire' => time() + 604800,
            ]);
            \Yii::$app->response->cookies->add($cookie);
        }
    }
    public function saveClear($event)
    {
        \yii\caching\TagDependency::invalidate(Yii::$app->frontend_cache, 'db_cache_catalog');
        parent::saveClear($event);
    }
    private $_real_price = false;
    public function real_price()
    {
        if ($this->_real_price === false) {
            if ($this->discount && $this->price > 0) {
                $proc = 100 - $this->discount;
                $price = ((float)$this->price * $proc) / 100;
                $this->old_price = $this->price;
                $this->price = $price;
            }
            $this->_real_price = true;
        }
        return $this->price;
    }
    public function sum_price($count = 1)
    {
        return $this->price * $count;
    }
    public function real_sum_price($count = 1)
    {
        return $this->real_price() * $count;
    }
    /**
     * @param $type
     * @param int|bool $limit
     * @param bool $return_q
     * @return self[]|\yii\db\ActiveQuery
     */
    public static function list_items($type, $limit = false, $return_q = false)
    {
        $q = self::find()
            ->andWhere(['isVisible' => 1])
            ->with(['itemImgs', 'categories']);
        switch ($type) {
            case 'popularity':
                $q->andWhere('popularity>0')
                    ->orderBy(['popularity' => SORT_DESC]);
                break;
            case 'hit':
                $q->andWhere(['isHit' => 1])
                    ->orderBy(['updated_at' => SORT_DESC]);
                break;
            case 'day':
                $q->andWhere(['isDay' => 1])
                    ->orderBy(['updated_at' => SORT_DESC]);
                break;
            case 'new':
                $q->andWhere(['isNew' => 1])
                    ->orderBy(['updated_at' => SORT_DESC]);
                break;
            case 'sale':
                $q->andWhere(['isSale' => 1])
                    ->orderBy(['updated_at' => SORT_DESC]);
                break;
            default:
                break;
        }
        if ($limit) {
            $q->limit($limit);
        }
        if (!$return_q) {
            return self::getDb()->cache(
                function ($db) use ($q) {
                    return $q->all();
                },
                86400,
                new \yii\caching\TagDependency(['tags' => 'db_cache_catalog'])
            );
        } else {
            return $q;
        }
    }

    public static function sliders_items()
    {
        $blocks = \Yii::$app->cache->get([
            'index_slider_items_array',
        ]);
        if ($blocks === false) {
            $blocks = [];
            \Yii::$app->controller->view->params['slider_index_block'] = [];
            $items = Items::list_items('new', 12, true)
                ->with([
                    'itemOptionsValues' => function ($q) {
                        /** @var \yii\db\ActiveQuery $q */
                        $q->with(['option', 'optionValue'])
                            ->join('LEFT JOIN', 'options_category', '`options_category`.`option_id` = `item_options_value`.`option_id`')
                            ->join('LEFT JOIN', 'options', '`options`.`id` = `item_options_value`.`option_id`')
                            ->andWhere(['OR', ['options_category.isList' => 1], ['options.isList' => 1]]);
                    }
                ])
                ->all();
            $cats = Category::find()->andWhere(['items.isVisible' => 1, 'items.isNew' => 1])
                ->join('LEFT JOIN', 'items', '`items`.`cid` = `category`.`id`')
                ->groupBy(['`category`.`id`'])
                ->all();
            $blocks['new']['full'] = \Yii::$app->controller->renderPartial(
                '//blocks/index_slider_items',
                [
                    'items' => $items,
                    'cats' => $cats,
                    'title' => 'Новое в каталоге',
                    'all' => 'Все новинки',
                    'key' => 'new'
                ]
            );
            $blocks['new']['cats'] = \Yii::$app->controller->view->params['slider_index_block'];
            \Yii::$app->controller->view->params['slider_index_block'] = [];
            $items = Items::list_items('sale', 12, true)
                ->with([
                    'itemOptionsValues' => function ($q) {
                        /** @var \yii\db\ActiveQuery $q */
                        $q->with(['option', 'optionValue'])
                            ->join('LEFT JOIN', 'options_category', '`options_category`.`option_id` = `item_options_value`.`option_id`')
                            ->join('LEFT JOIN', 'options', '`options`.`id` = `item_options_value`.`option_id`')
                            ->andWhere(['OR', ['options_category.isList' => 1], ['options.isList' => 1]]);
                    }
                ])
                ->all();
            $cats = Category::find()->andWhere(['items.isVisible' => 1, 'items.isSale' => 1])
                ->join('LEFT JOIN', 'items', '`items`.`cid` = `category`.`id`')
                ->groupBy(['`category`.`id`'])
                ->all();
            $blocks['sale']['full'] = \Yii::$app->controller->renderPartial(
                '//blocks/index_slider_items',
                [
                    'items' => $items,
                    'cats' => $cats,
                    'title' => 'Распродажа',
                    'all' => 'Все товары',
                    'key' => 'sale'
                ]
            );
            $blocks['sale']['cats'] = \Yii::$app->controller->view->params['slider_index_block'];
            \Yii::$app->controller->view->params['slider_index_block'] = [];
            $items = Items::list_items('hit', 12, true)
                ->with([
                    'itemOptionsValues' => function ($q) {
                        /** @var \yii\db\ActiveQuery $q */
                        $q->with(['option', 'optionValue'])
                            ->join('LEFT JOIN', 'options_category', '`options_category`.`option_id` = `item_options_value`.`option_id`')
                            ->join('LEFT JOIN', 'options', '`options`.`id` = `item_options_value`.`option_id`')
                            ->andWhere(['OR', ['options_category.isList' => 1], ['options.isList' => 1]]);
                    }
                ])
                ->all();
            $cats = Category::find()->andWhere(['items.isVisible' => 1, 'items.isHit' => 1])
                ->join('LEFT JOIN', 'items', '`items`.`cid` = `category`.`id`')
                ->groupBy(['`category`.`id`'])
                ->all();
            $blocks['hit']['full'] = \Yii::$app->controller->renderPartial(
                '//blocks/index_slider_items',
                [
                    'items' => $items,
                    'cats' => $cats,
                    'title' => 'Топовые товары',
                    'all' => 'Все товары',
                    'key' => 'hit'
                ]
            );
            $blocks['hit']['cats'] = \Yii::$app->controller->view->params['slider_index_block'];
            \Yii::$app->cache->set(
                [
                    'index_slider_items_array',
                ],
                $blocks,
                86400,
                new TagDependency(['tags' => 'db_cache_catalog'])
            );
        }
        return $blocks;
    }
}
