<?php
namespace backend\modules\catalog\models;

use common\models\User;
use yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\helpers\Inflector;
use shadow\widgets\CKEditor;

/**
 * This is the model class for table "item_questions".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $item_id
 * @property string $name
 * @property string $email
 * @property string $body
 * @property string $body_answer
 * @property integer $isVisible
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property Items $item
 * @property User $user
 */
class ItemQuestions extends \shadow\SActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_questions';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'item_id', 'isVisible'], 'integer'],
            [['item_id', 'name', 'body'], 'required'],
            [['body', 'body_answer'], 'string'],
            [['name', 'email'], 'string', 'max' => 255],
            ['item_id', 'exist', 'skipOnError' => true, 'targetClass' => Items::className(), 'targetAttribute' => ['item_id' => 'id']],
            ['user_id', 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'Пользователь',
            'item_id' => 'Товар',
            'name' => 'Имя',
            'email' => 'E-Mail',
            'body' => 'Вопрос',
            'body_answer' => 'Ответ',
            'isVisible' => 'Видимость',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At'
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(Items::className(), ['id' => 'item_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className()
        ];
    }
    public function FormParams()
    {
        if ($this->isNewRecord) {
            $this->loadDefaultValues(true);
        }
        $controller_name = Inflector::camel2id(Yii::$app->controller->id);
        $fields = [
            'isVisible' => [
                'type' => 'checkbox'
            ],
            'user_id' => [
                'type' => 'dropDownList',
                'relation' => [
                    'class' => User::className()
                ]
            ],
            'item_id' => [
                'type' => 'dropDownList',
                'relation' => [
                    'class' => Items::className()
                ]
            ],
            'name' => [],
            'email' => [],
            'body' => [
                'type' => 'textArea',
                'widget' => [
                    'class' => CKEditor::className(),
                    'config' => [
                        'editorOptions' => [
                            'enterMode' => 2
                        ]
                    ]
                ]
            ],
            'body_answer' => [
                'type' => 'textArea',
                'widget' => [
                    'class' => CKEditor::className(),
                    'config' => [
                        'editorOptions' => [
                            'enterMode' => 2
                        ]
                    ]
                ]
            ]
        ];
        $result = [
            'form_action' => [$controller_name . '/save'],
            'cancel' => [$controller_name . '/index'],
            'groups' => [
                'main' => [
                    'title' => 'Основное',
                    'icon' => 'suitcase',
                    'options' => [],
                    'fields' => $fields
                ]
            ]
        ];
        return $result;
    }
    public function afterSave($insert, $changedAttributes)
    {
        $sql_count_reviews=new Expression(
            '(select COUNT(*) from `item_questions` WHERE `item_questions`.`item_id`=:item_id AND `item_questions`.isVisible=1 group by `item_questions`.`item_id`)',
            [':item_id'=>$this->item_id]
        );
        Items::updateAll(['count_questions'=>$sql_count_reviews], ['id' => $this->item_id]);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
