<?php

namespace backend\modules\catalog\models;

use common\models\User;
use yii;
use yii\behaviors\TimestampBehavior;
use yii\db\Expression;
use yii\helpers\Inflector;
use shadow\widgets\CKEditor;

/**
 * This is the model class for table "item_reviews".
 *
 * @property integer $id
 * @property integer $user_id
 * @property integer $item_id
 * @property integer $rate
 * @property string  $name
 * @property string  $body
 * @property integer $isVisible
 * @property integer $created_at
 * @property integer $updated_at
 *
 * @property Items   $item
 * @property User    $user
 */
class ItemReviews extends \shadow\SActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_reviews';
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'item_id', 'rate', 'isVisible'], 'integer'],
            [['rate'], 'integer', 'min' => 1, 'max' => 5],
            [['item_id', 'rate', 'name', 'body'], 'required'],
            [['body'], 'string'],
            [['name'], 'string', 'max' => 255],
            ['item_id', 'exist', 'skipOnError' => true, 'targetClass' => Items::className(), 'targetAttribute' => ['item_id' => 'id']],
            ['user_id', 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id'         => 'ID',
            'user_id'    => 'Пользователь',
            'item_id'    => 'Товар',
            'rate'       => 'Оценка',
            'name'       => 'Имя',
            'body'       => 'Отзыв',
            'isVisible'  => 'Видимость',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At'
        ];
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItem()
    {
        return $this->hasOne(Items::className(), ['id' => 'item_id']);
    }
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className()
        ];
    }
    public function FormParams()
    {
        if ($this->isNewRecord) {
            $this->loadDefaultValues(true);
        }
        $controller_name = Inflector::camel2id(Yii::$app->controller->id);
        $fields          = [
            'isVisible' => [
                'type' => 'checkbox'
            ],
            'user_id'   => [
                'type'     => 'dropDownList',
                'relation' => [
                    'class' => User::className(),
                    'label' => 'username'
                ]
            ],
            'item_id'   => [
                'type'     => 'dropDownList',
                'relation' => [
                    'class' => Items::className()
                ]
            ],
            'rate'      => [],
            'name'      => [],
            'body'      => [
                'type'   => 'textArea',
                'widget' => [
                    'class'  => CKEditor::className(),
                    'config' => [
                        'editorOptions' => [
                            'enterMode' => 0
                        ]
                    ]
                ]
            ]
        ];
        $result          = [
            'form_action' => [$controller_name . '/save'],
            'cancel'      => [$controller_name . '/index'],
            'groups'      => [
                'main' => [
                    'title'   => 'Основное',
                    'icon'    => 'suitcase',
                    'options' => [],
                    'fields'  => $fields
                ]
            ]
        ];
        return $result;
    }
    public function afterSave($insert, $changedAttributes)
    {
        $sql_rate          = new Expression(
            '(select avg(rate) from `item_reviews` WHERE `item_reviews`.`item_id`=:item_id AND `item_reviews`.isVisible=1 group by `item_reviews`.`item_id`)',
            [':item_id' => $this->item_id]
        );
        $sql_count_reviews = new Expression(
            '(select COUNT(*) from `item_reviews` WHERE `item_reviews`.`item_id`=:item_id AND `item_reviews`.isVisible=1 group by `item_reviews`.`item_id`)',
            [':item_id' => $this->item_id]
        );
        Items::updateAll(['rate' => $sql_rate, 'count_reviews' => $sql_count_reviews], ['id' => $this->item_id]);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}