<?php

namespace backend\modules\catalog\controllers;

use backend\AdminController;
use backend\modules\catalog\models\Items;
use common\models\BonusSettings;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;

class BonusSettingsController extends AdminController
{
    public function init()
    {
        $this->model       = new BonusSettings();
        $controller_name   = Inflector::camel2id($this->id);
        $this->url         = [
            'back'    => ["$controller_name/index"],
            'control' => ["$controller_name/control"]
        ];
        $this->view->title = 'Настройки бонусов';
        $this->MenuActive($controller_name);
        $this->breadcrumb[] = [
            'url'   => ["$controller_name/index"],
            'label' => 'Настройки бонусов'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs'  => [
                'class'   => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $data['items'] = BonusSettings::find()->orderBy(['price_start' => SORT_ASC])->all();
        return $this->render('index', $data);
    }
}