<?php

namespace backend\modules\catalog\controllers;


use common\components\Debugger as d;
use backend\AdminController;
use backend\models\SUser;
use backend\modules\catalog\models\DeliveryPrice;
use backend\modules\catalog\models\Items;
use backend\modules\catalog\models\Orders;
use backend\modules\catalog\models\OrdersItems;
use backend\modules\catalog\models\OrdersPay;
use common\models\User;
use common\models\UserAddress;
use shadow\widgets\AdminActiveForm;
use Yii;
use yii\db\ActiveQuery;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Json;
use yii\helpers\Url;
use yii\web\BadRequestHttpException;
use yii\web\Response;
use common\models\OrdersRollbackItems;

/**
 * Class OrdersController
 * @package backend\controllers
 * @property Orders $model
 */
class OrdersController extends AdminController
{
    public $model;

    public function init()
    {
        $this->model = new Orders();
        $this->url = [
            'back' => ['orders/index'],
            'control' => ['orders/control'],
        ];
        $this->view->title = 'Заказы';
        $this->MenuActive('orders');
        $this->breadcrumb[] = [
            'url' => ['orders/index'],
            'label' => 'Заказы',
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
//                    'filter' => ['post', 'get'],
                ],
            ],
        ];
    }

    public function beforeAction($action)
    {

//        d::pe(Yii::$app->controller->action->id);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionFilter()
    {
        /**
         * @var $items Orders[]
         */
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $request = Yii::$app->request;
            $columns = $request->get('columns');
            $q_all = new ActiveQuery(Orders::className());
            if (!Yii::$app->user->can('admin') && !Yii::$app->user->can('manager')) {
                if (Yii::$app->user->can('collector')) {
                    $q_all->andWhere(['`orders`.status' => [1, 2, 3, 4]]);
                } elseif (Yii::$app->user->can('driver')) {
                    $q_all->andWhere(['`orders`.status' => [3, 4]]);
                }
            }
            $full_count = $q_all->count();
            $q = new ActiveQuery(Orders::className());
            if (!Yii::$app->user->can('admin') && !Yii::$app->user->can('manager')) {
                if (Yii::$app->user->can('collector')) {
                    $q->andWhere(['`orders`.status' => [1, 2, 3, 4]]);
                } elseif (Yii::$app->user->can('driver')) {
                    $q->andWhere(['`orders`.status' => [3, 4, 5]]);
                }
            }
            foreach ($columns as $column) {
                $val = $column['search']['value'];
                $name = $column['data'];
                if ($val !== '') {
                    switch ($name) {
                        case 'date_delivery':
                        case 'created_at':
                            Orders::searchTimeRow($q, $name, $val);
                            break;
                        case 'performer':
                            $q->andWhere(
                                [
                                    'or',
                                    ['`orders`.manager_id' => $val],
                                    ['`orders`.collector_id' => $val],
                                    ['`orders`.driver_id' => $val],
                                ]
                            );
                            break;
                        default:
                            $q->andWhere(['`orders`.' . $name => $val]);
                            break;
                    }
                }
                $name = $val = null;
            }
            $search = $request->get('search');
            if (isset($search['value']) && $search['value'] !== '') {
                $q->join('LEFT OUTER JOIN', '`orders_items`', '`orders_items`.`order_id`=`orders`.`id`');
                $q->join('LEFT OUTER JOIN', '`items`', '`orders_items`.`item_id`=`items`.`id`');
                $q->andWhere(
                    [
                        'OR',
                        ['like', '`orders`.user_name', $search['value']],
                        ['like', '`orders`.id', $search['value']],
                        ['like', '`items`.name', $search['value']],
                    ]
                );
                $q->groupBy(['`orders`.id']);
            }
            if ($orders = $request->get('order')) {
                $q_order = [];
                foreach ($orders as $order) {
                    $name = $columns[$order['column']]['data'];
                    $q_order['`orders`.' . $name] = ($order['dir'] == 'asc') ? SORT_ASC : SORT_DESC;
                }
                if ($q_order) {
                    $q->orderBy($q_order);
                }
            }
            $count = $q->count();
            $result = [
                'draw' => (int)$request->get('draw'),
                'recordTotal' => (int)$full_count,
                'recordsFiltered' => (int)$count,
            ];
            if ($page = $request->get('start')) {
                $q->offset($page);
            }
            $q->limit($request->get('length'));
            $items = $q->all();
            $data_items = [];
            $default_columns = [
                'full_price',
                'id',
                'user_phone',
                'user_address',
                'payment',
                'pay_status',
                'pay_status_text',
                'delivery'
            ];
            foreach ($items as $item) {
                $data_item = [];
                foreach ($columns as $column) {
                    $data_item[$column['data']] = $item->getRow($column['data']);
                }
                foreach ($default_columns as $val) {
                    $data_item[$val] = $item->getRow($val);
                }
                $data_items[] = $data_item;
            }
            $result['data'] = $data_items;

            return $result;
        } else {
            throw new BadRequestHttpException();
        }
    }

    public function actionItems()
    {
        /**
         * @var $items Items[]
         */
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $result = [];
            $search = Yii::$app->request->get('search');
            $ids = Yii::$app->request->get('ids', []);
            $ids = array_diff($ids, ['']);
            $q = new ActiveQuery(Items::className());
            $q->where(
                [
                    'and',
                    ['not in', 'id', $ids],
                    [
                        'or',
                        ['like', 'name', $search],
                        ['like', 'id', $search],
                    ],
                ]
            );
            $q->limit(100);
            $items = $q->all();
            foreach ($items as $item) {
                $result[] = [
                    'id' => $item->id,
                    'value' => $item->vendor_code . ' : ' . $item->name,
                ];
            }

            return $result;
        } else {
            throw new BadRequestHttpException();
        }
    }

    public function actionAddItem($id)
    {
        /**
         * @var $items Items[]
         */
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $item = Items::findOne($id);
            $result = [
                'id' => $id,
                'item' => $this->renderPartial(
                    'item', [
                        'item' => $item,
                        'name' => 'ordersItems',
                        'isWholesale' => Yii::$app->request->get('isWholesale'),
                    ]
                ),
            ];

            return $result;
        } else {
            throw new BadRequestHttpException();
        }
    }

    public function actionSets()
    {
        /**
         * @var $items Sets[]
         */
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $result = [];
            $search = Yii::$app->request->get('search');
            $ids = Yii::$app->request->get('ids', []);
            $ids = array_diff($ids, ['']);
            $q = new ActiveQuery(Sets::className());
            $q->where(
                [
                    'and',
                    ['not in', 'id', $ids],
                    [
                        'or',
                        ['like', 'name', $search],
                        ['like', 'id', $search],
                    ],
                ]
            );
            $q->limit(100);
            $items = $q->all();
            foreach ($items as $item) {
                $result[] = [
                    'id' => $item->id,
                    'value' => $item->name,
                ];
            }

            return $result;
        } else {
            throw new BadRequestHttpException();
        }
    }

    public function actionAddSet($id)
    {
        /**
         * @var $items Sets[]
         */
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $item = Sets::findOne($id);
            $result = [
                'id' => $id,
                'item' => $this->renderPartial('set', ['item' => $item, 'name' => 'ordersSets']),
            ];

            return $result;
        } else {
            throw new BadRequestHttpException();
        }
    }

    public function actionControl()
    {
        $item = $this->model;
        if ($id = \Yii::$app->request->get('id')) {
            $item = $item->findOne($id);
            if ($item) {
                $this->breadcrumb[] = [
                    'url' => '#',
                    'label' => 'Заказ №' . $item->id,
                ];
            }
        } else {
            if ($user_id = Yii::$app->request->get('user_id')) {
                /**@var $user User */
                $user = User::findOne($user_id);
                if ($user) {
                    $item->user_id = $user->id;
                    $item->user_name = $user->username;
                    $item->user_mail = $user->email;
                    $item->user_phone = $user->phone;
                    $item->isEntity = $user->isEntity;
                    $item->isWholesale = $user->isWholesale;
                    /**@var $a_address UserAddress */
                    $a_address = UserAddress::find()->andWhere(['user_id' => $user->id])->orderBy(
                        ['isMain' => SORT_DESC]
                    )->one();
                    if ($a_address) {
                        $item->user_address = 'г.' . $a_address->data_city[$a_address->city] . ', ул. ' . $a_address->street . ', дом. ' . $a_address->home . (($a_address->house) ? (', кв. ' . $a_address->house) : '');
                        $item->city_id = $a_address->city;
                    }
                    if ($item->isWholesale == 1) {
                        $item->enable_bonus = 0;
                    }
                }
            }
        }



        $data['item'] = $item;
        if ($data['item']) {
            return $this->render('form', $data);
        } else {
            return false;
        }
    }

    public function actionSave()
    {
        $record = $this->model;
        $post = Yii::$app->request->post();
        if ($id = $post['id']) {
            $record = $record->findOne($id);
        }

//        d::pe($post);

        $is_manager = (Yii::$app->user->can('manager') || Yii::$app->user->can('manager'));
        $is_collector = (Yii::$app->user->can('collector'));
        $is_driver = (Yii::$app->user->can('driver'));
        $is_admin = Yii::$app->user->can('admin');
        /**@var $user_panel \backend\models\SUser */
        $user_panel = Yii::$app->user->identity;
        if ($is_admin) {
            $record->scenario = 'admin';
        } else {
            if (($is_collector || $is_manager) && $record->status < 5) {
                $record->scenario = 'collector';
            }
            if ($is_manager && $record->status == 0) {
                $record->scenario = 'manager';
            }
        }
        if ($record->load(Yii::$app->request->post())) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                if ($user_id = Yii::$app->request->post('user_id')) {
                    $record->user_id = $user_id;
                }

                if (
                    !$record->isNewRecord &&
                    $user_panel->role == 'manager' &&
                    !Yii::$app->request->post('lock') &&
                    !$record->manager_id
                ) {
//                    d::pe('Необходимо сначала принять заказ!');
                    $result['message']['error'] = 'Необходимо сначала принять заказ!';

                    return $result;
                }

                if ($errors = AdminActiveForm::validate($record)) {
                    $result['errors'] = $errors;
                } else {
                    $back = false;
                    if ($is_manager && $record->isNewRecord) {
//                        d::pe('$is_manager && $record->isNewRecord');
                        $record->manager_id = Yii::$app->user->id;
                        $record->status = 0;
                    }
                    $status = $record->status;

                    if (!$is_manager || !($is_manager && ($status == 0 || $status == 1))) {
//                        d::pe('if1');
                        if (($is_collector || $is_manager) && $record->status < 5) {
//                            d::pe('if1 1');
                            $driver_id = $record->driver_id;
                        }
//                        $admin_comments = $record->admin_comments;
//                        $record->attributes = $record->oldAttributes;
//                        $record->admin_comments = $admin_comments;
                        if (isset($driver_id)) {
//                            d::pe('if1 2');
                            $record->driver_id = $driver_id;
                        }
                    }

                    if ($lock = $record->lock($is_manager, $is_collector, $is_driver)) {
//                        d::pe('return $lock');
                        return $lock;
                    }

                    if ($unlock = $record->unlock($is_manager, $is_collector, $is_driver)) {
//                        d::pe('return $unlock');
                        return $unlock;
                    }
                    if (!$is_admin && ($is_manager && $record->manager_id && $record->manager_id != Yii::$app->user->id)) {
//                        d::pe('Данный заказ уже принят другим менеджером');
                        $result['message']['error'] = 'Данный заказ уже принят другим менеджером';

                        return $result;
                    }
                    if (in_array($record->status, [5, 6, 7])) {
//                        d::pe('Данный заказ уже закрыт');
                        $result['message']['error'] = 'Данный заказ уже закрыт';

                        return $result;
                    }

                    /*
                     * Кнопки
                     * "Принять","На сборку","Подтвердить",красная кнопка "Возврат",
                     * запускают этот IF
                     */
                    if (($is_collector || $is_manager) && $record->status != 5) {

                        if (!$is_admin && $is_collector && ($record->collector_id && $record->collector_id != Yii::$app->user->id)) {
//                            d::pe('Данный заказ уже принят другим сборщиком');
                            $result['message']['error'] = 'Данный заказ уже принят другим сборщиком';

                            return $result;
                        }

                        if ($no_phone = Yii::$app->request->post('no_phone')) {
                            // Не запускается если нет телефона
//                            d::pe('if3');
                            if ($no_phone == 1) {
                                $record->status = 9;
                                $record->update_status = 9;
                                $back = true;
                            } elseif ($no_phone == 2) {
                                $record->update_status = 13;
                                if ($record->driver_id) {
                                    $record->status = 3;
                                } else {
                                    $record->status = 0;
                                }
                            }
                        }

                        if (Yii::$app->request->post('no')) {
                            // Не запускается
//                            d::pe('if post->no');
                            if ($record->status != 8) {
                                $record->rollbackBonus();
                            }
                            $record->status = 8;
                            $back = true;
                            $record->update_status = 14;
                        }
//                        d::pe($record);
                        $record->UpdateOrderItems();
                    }

                    if (Yii::$app->request->post('commit')) {
//                        d::pe('commit');
                        $back = true;
                    }



                    if ($success = $record->success($is_manager, $is_collector, $is_driver)) {
//                        d::pe('$success');
//                        d::pe($success);
                        if (isset($success['back'])) {
//                            d::pe('$success 1');
                            $back = true;
                        } else {
//                            d::pe('$success 2');
                            // Красная кнопка "Возврат" тут возвращает url для JS-редиректа
                            return $success;
                        }
                    }

//                    d::pe('bSave');
                    $save = $record->save();
                    if ($save) {
//                    if (1) {
                        if ($is_collector || $is_manager) {
                            $record->saveOrderItems();
                        }
                        if ($back) {
                            $result['url'] = Url::to($this->url['back']);
                        } else {
                            $url = $this->url['control'];
                            $url['id'] = $record->id;
                            $result['url'] = Url::to($url);
                        }
                        if (Yii::$app->request->post('send_message')) {
//                            d::pe('send_message');
                            unset($result['url']);
                            $url_send_message = Json::encode(Url::to(['orders/send-message', 'id' => $record->id]));
                            $render_message = $this->renderPartial('@common/mail/order', ['order' => $record]);
                            $html_message = Json::encode(
                                '<form><textarea class="form-control" id="send_message_order" name="message" >' . $render_message . '</textarea></form>'
                            );
                            $result['js'] = <<<JS
var form = $({$html_message});

var box_message = bootbox.confirm(form, function (result) {
    if (result) {
        if (CKEDITOR && CKEDITOR.instances['send_message_order']) {
            CKEDITOR.instances['send_message_order'].updateElement();
        }
        var body_message = form.find('textarea').val();
        $.ajax({
            url: {$url_send_message},
            type: 'POST',
            data: $(form).serialize(),
            dataType: 'JSON',
            success: function (data) {
                $.growl.notice({title: 'Оповещение', message: data.success});
            },
            error: function () {
                $.growl.error({title: 'Ошибка', message: "Произошла ошибка на стороне сервера!", duration: 5000});
            }
        })
    }
});
box_message.on("shown.bs.modal", function () {
    CKEDITOR.replace('send_message_order', {
        //enterMode: 2,
        toolbar: 'Basic'
    });
});

JS;
                        } else {
//                            d::pe('send_message else');
                            if ($record->status < 5 && $record->payment == 2 && ($add_sum = $record->addSumPay())) {
                                $redirect_url = '';
                                if (isset($result['url'])) {
                                    $redirect_url = $result['url'];
                                    unset($result['url']);
                                }
                                $add_url_pay = Json::encode(Url::to(['orders/send-pay', 'id' => $record->id]));
                                $result['js'] = <<<JS
    bootbox.confirm({
        message: 'Необходима оплата в размере: <br/> {$add_sum} тенге',
        buttons: {
            confirm: {
                label: 'Запросить оплату',
                className: 'btn-success'
            },
            cancel: {
                label: 'Закрыть',
                className: 'btn-danger'
            }
        },
        callback: function (result) {
            if (result) {
                $.ajax({
                    url: {$add_url_pay},
                    type: 'GET',
                    dataType: 'JSON',
                    success: function (data) {
                        if (typeof data.error != 'undefined') {
                            $.growl.error({title: 'Ошибка', message: data.error, duration: 5000});
                        }
                        if (typeof data.success != 'undefined') {
                            $.growl.notice({title: 'Успех', message: message.success});
                            if (typeof data.url != 'undefined'){
                                bootbox.confirm({
                                    message: 'Запрос отправлен в систему, для ручной отправки скопируйте эту ссылку:<br/> '+data.url,
                                    buttons: {
                                        confirm: {
                                            label: 'Ок'
                                        }
                                    },
                                    callback:function(result) {
                                        if ('{$redirect_url}'){
                                           window.location='{$redirect_url}';
                                        }
                                    }
                                }).cancel({
                                    message: 'Запрос отменён<br/> '+data.url,
                                    buttons: {
                                        confirm: {
                                            label: 'Ок'
                                        }
                                    },
                                    callback:function(result) {
                                        if ('{$redirect_url}'){
                                           window.location='{$redirect_url}';
                                        }
                                    }
                                });
                            }
                            // window.location.reload();
                        }
                    },
                    error: function () {
                        $.growl.error({title: 'Ошибка', message: 'Произошла ошибка на стороне сервера!', duration: 5000});
                    }
                })

            }
        },
        className: "bootbox-sm"
    });
JS;
                            } else {
                                $result['message']['success'] = 'Сохранено!';
                            }
                        }
                        $result['set_value']['id'] = $record->id;
                        $result['message']['success'] = 'Сохранено!';
                    } else {
                        $result['message']['error'] = 'Произошла ошибка!';
                    }
                }

//                d::pe($result);
                return $result;
            } else {
                $record->validate();
            }
        }
        if (!Yii::$app->request->isAjax) {
            return $this->goBack();
        }
    }

    public function actionRollbackItems($id)
    {
        /**
         * @var $item        Orders
         * @var $user        SUser
         * @var $target_item OrdersItems
         */

        $post = Yii::$app->request->post();
//        d::pe($post);

        $item = Orders::findOne($id);
        $user = Yii::$app->user->identity;
        if ($item && $item->status <= 4 && ($item->driver_id == $user->id || $item->manager_id == $user->id)) {
            if (Yii::$app->request->isAjax) {
                Yii::$app->response->format = Response::FORMAT_JSON;
                $main = new OrdersRollbackItems();
                $order_items = $item->getOrdersItems()->indexBy('item_id')->all();
//                $order_sets = $item->getOrdersSets()->indexBy('set_id')->all();
//                d::pe($main->type);
                $main->load(Yii::$app->request->post());
//                d::pe($main->type);
                $data_insert_items = $data_insert_sets = [];
                $rollback_items = Yii::$app->request->post('ordersItems', []);
                $rollback_sets = Yii::$app->request->post('ordersSets', []);
                if ($rollback_items) {
                    $i = 0;
                    foreach ($rollback_items as $key => &$val) {
                        $target_item = $order_items[$key];
                        $weight = (isset($val['weight']) ? doubleval($val['weight']) : 0);
                        $count = doubleval($val['count']);
                        $add_db = true;
                        if ($count > $target_item->count) {
                            $error = 'Количество товара не может быть больше чем в заказе<br>';
                            $error .= 'Товар:' . $target_item->item->name;
                            $error .= '<br>Количество в заказе:' . $target_item->count;
                            $result['message']['error'] = $error;

                            return $result;
                        }
                        if ($weight > $target_item->weight) {
                            $error = 'Вес товара не может быть больше чем в заказе<br>';
                            $error .= 'Товар:' . $target_item->item->name;
                            $error .= '<br>Вес в заказе:' . $target_item->weight;
                            $result['message']['error'] = $error;

                            return $result;
                        }
                        if ($main->type == 0) {
                            $count = $target_item->count;
                            $weight = $target_item->weight;
                            $val['weight'] = 0;
                            $val['count'] = 0;
                        } else {
                            if ($count < $target_item->count || $weight < $target_item->weight) {
                                $count = $target_item->count - $count;
                                $weight = $target_item->weight - $weight;
                                $val['weight'] = $target_item->weight - $weight;
                                $val['count'] = $target_item->count - $count;
                            } else {
                                $add_db = false;
                            }
                        }
                        if ($add_db) {
                            $data_insert_items[$i] = [
                                'order_id' => $item->id,
                                'item_order_id' => $target_item->id,
                                'count' => $count,
                                'weight' => $weight,
                            ];
                        }
                        $i++;
                    }
                }
//                if ($rollback_sets) {
//                    $i = 0;
//                    foreach ($rollback_sets as $key => &$val) {
//                        $target_item = $order_sets[$key];
//                        $count = doubleval($val['count']);
//                        $add_db = true;
//                        if ($count > $target_item->count) {
//                            $error = 'Количество сета не может быть больше чем в заказе';
//                            $error .= '<br>Сет:' . $target_item->item->name;
//                            $error .= '<br>Количество в заказе:' . $target_item->count;
//                            $result['message']['error'] = $error;
//
//                            return $result;
//                        }
//                        if ($main->type == 0) {
//                            $count = $target_item->count;
//                            $val['count'] = 0;
//                        } else {
//                            if ($count < $target_item->count) {
//                                $count = $target_item->count - $count;
//                                $val['count'] = $target_item->count - $count;
//                            } else {
//                                $add_db = false;
//                            }
//                        }
//                        if ($add_db) {
//                            $data_insert_sets[$i] = [
//                                'order_id' => $item->id,
//                                'set_order_id' => $target_item->id,
//                                'count' => $count,
//                            ];
//                        }
//                        $i++;
//                    }
//                }
                $item->UpdateOrderItems($rollback_items, $rollback_sets, true);

                $item->status = 10;

//                d::pe($main);
                if ($main->type == 0) {
                    //полный возврат
                    $item->status = 6;// 6
                    $item->rollbackBonus();
                    $item->update_status = 8;
                } else {
                    //частичный возврат
                    $item->status = 7;
                    $item->commitBonus();
                    $item->update_status = 7;
                }
                if ($item->save(false)) {
                    if ($data_insert_items) {
                        Yii::$app->db->createCommand()->batchInsert(
                            OrdersRollbackItems::tableName(), [
                            'order_id',
                            'item_order_id',
                            'count',
                            'weight',
                        ], $data_insert_items
                        )->execute();
                    }
                    if ($data_insert_sets) {
                        Yii::$app->db->createCommand()->batchInsert(
                            OrdersRollbackSets::tableName(), [
                            'order_id',
                            'set_order_id',
                            'count',
                        ], $data_insert_sets
                        )->execute();
                    }
                    $result['url'] = Url::to($this->url['back']);
                } else {
                    $result['message']['error'] = 'Произошла ошибка!';
                }

                return $result;
            } else {
                $this->view->title = 'Возврат';

                return $this->render('rollback_items', ['order' => $item]);
            }
        } else {
            throw new BadRequestHttpException();
        }
    }

    public function actionChangeItem()
    {
        /**
         * @var $order_item  OrdersItems
         * @var $target_item Items
         */
        if ($id = Yii::$app->request->post('id')) {
            $order = Orders::findOne($id);
        } else {
            $order = new Orders();
        }
        $order->isWholesale = Yii::$app->request->post('isWholesale');
        $order->discount = Yii::$app->request->post('discount');
        $order->price_delivery = Yii::$app->request->post('delivery');
        $sum = $full_bonus_manager = $full_purch_price = 0;
        $result_items = $result_sets = [];
        if ($items = Yii::$app->request->post('ordersItems')) {
            $db_items = Items::find()->indexBy('id')->where(['id' => array_keys($items)])->all();
            /**
             * @var $functions \frontend\components\FunctionComponent
             */
            $functions = Yii::$app->function_system;
            $sessions_items = $order->to_session_items($items);
            $old_items = [];
            if (!$order->isNewRecord) {
                $old_items = $order->getOrdersItems()->indexBy('item_id')->all();
                $db_items = $order->convert_all_to_model($old_items, $db_items);
            }
            if (!trim($order->discount)) {
                if ($order->isWholesale == 0) {
                    $discount = $functions->discount_sale_items($db_items, $sessions_items);
                } else {
                    $discount = [];
                }
            } else {
                $discount = [];
            }
            foreach ($items as $key => $value) {
                $count = doubleval($value['count']);
                $weight = doubleval((isset($value['weight']) ? $value['weight'] : 0));
                $order_item = false;
                if (isset($old_items[$key])) {
                    $order_item = $old_items[$key];
                    $target_item = $db_items[$order_item->item_id];
                } else {
                    $target_item = $db_items[$key];
                }
                if (isset($value['price'])) {
                    if ($target_item->discount) {
                        $target_item->discount = 0;
                    }
                    $target_item->price = (int)$value['price'];
                } else {
                    if ($target_item->discount) {
                        $target_item->discount = 0;
                    }
                    if ($order_item) {
                        $target_item->price = $order_item->price;
                    }
                }
                $item_price = $target_item->sum_price($count);
                $full_item_price = $functions->full_item_price($discount, $target_item, $count, $weight);
//                $full_bonus_manager += $target_item->full_price_bonus_manager($count, $weight, $discount);
                $discount_price = '';
                if (isset($discount)) {
                    $discount_price = ($item_price - $full_item_price);
                    $item_price = $item_price - $discount_price;
                }
                $result_items[$target_item->id] = [
                    'price' => $item_price,
                    'discount' => $discount_price,
                ];
                $sum += $item_price;
            }
        }
//        /**
//         * @var $db_sets Sets[]
//         * @var $old_sets OrdersSets[]
//         */
//        if ($sets = Yii::$app->request->post('ordersSets')) {
//            $old_sets = [];
//            if (!$order->isNewRecord) {
//                $old_sets = $order->getOrdersSets()->indexBy('set_id')->all();
//            }
//            $db_sets = Sets::find()->indexBy('id')->where(['id' => array_keys($sets)])->all();
//            foreach ($sets as $key => $value) {
//                $count = doubleval($value['count']);
//                if (isset($old_sets[$key])) {
//                    $order_set = $old_sets[$key];
//                    if (isset($value['price'])) {
//                        $order_set->price = (int)$value['price'];
//                    }
//                    $target_set = $db_sets[$order_set->set_id];
//                    $set_price = round($count * $order_set->price);
//                    unset($old_sets[$key]);
//                } else {
//                    $target_set = $db_sets[$key];
//                    if (isset($value['price'])) {
//                        $target_set->price = (int)$value['price'];
//                    }
//                    $set_price = round($count * $target_set->real_price());
//                }
//                $sum += $set_price;
//                $bonus = $target_set->price_bonus_manager();
//                $full_bonus_manager += round($count * $bonus);
//                $result_sets[$target_set->id] = [
//                    'price' => $set_price
//                ];
//            }
//        }
        $order->bonus_manager = $full_bonus_manager - $order->discount($full_bonus_manager);
        $result = [
            'items' => $result_items,
            'sets' => $result_sets,
            'sum' => $sum,
            'full_price' => ((($sum + $order->price_delivery) - $order->discount($sum)) - $order->bonus_use),
            'full_bonus_manager' => $order->bonus_manager,
        ];
        Yii::$app->response->format = Response::FORMAT_JSON;

        return $result;
    }

    public function actionSendMessage()
    {
        if (Yii::$app->request->isAjax && ($id = Yii::$app->request->get('id'))) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            /**
             * @var $order Orders
             */
            $order = Orders::findOne($id);
            $result = [];
            $result['success'] = 'Письмо отправлено!';
            if ($order && ($message = Yii::$app->request->post('message')) && $order->user_mail) {
                \Yii::$app->mailer->compose()
                    ->setHtmlBody($message)
                    ->setFrom(
                        [\Yii::$app->params['supportEmail'] => 'Интернет-магазин ' . \Yii::$app->params['siteName'] . '.kz']
                    )
                    ->setTo($order->user_mail)
                    ->setSubject('Оповещение с сайте ' . \Yii::$app->params['siteName'] . '.kz')->send();
            } elseif (!$order->user_mail) {
                $result['success'] = 'E-Mail не указан!';
            }

            return $result;
        } else {
            throw new BadRequestHttpException();
        }
    }

    public function actionPrint($id)
    {
        $data = [
            'order' => Orders::findOne($id),
        ];
        $this->layout = '//empty';

        return $this->render('print', $data);
    }

    public function actionExport($date_start, $date_end)
    {
        $q = new ActiveQuery(Orders::className());
        if ($date_start) {
            $date = \DateTime::createFromFormat(
                'd.m.Y H:i:s', $date_start . ' 00:00:00', new \DateTimeZone(Yii::$app->timeZone)
            );
            $q->andWhere(['>=', '`created_at`', $date->getTimestamp()]);
        }
        if ($date_end) {
            $date = \DateTime::createFromFormat(
                'd.m.Y H:i:s', $date_end . ' 00:00:00', new \DateTimeZone(Yii::$app->timeZone)
            );
            $q->andWhere(['<=', '`created_at`', $date->getTimestamp()]);
        }
        $city_all = DeliveryPrice::find()->indexBy('id')->all();
        /**
         * @var $users_all SUser[]
         */
        $users_all = SUser::find()->indexBy('id')->all();
        $columns = [
            [
                'attribute' => 'id',
                'header' => 'id',
                'format' => 'text',
                'value' => function ($model) {
                    return $model->id;
                },
            ],
            [
                'attribute' => 'created_at',
                'header' => 'Дата заказа',
                'format' => 'text',
                'value' => function ($model) {
                    /**
                     * @var $model Orders
                     */
                    return $model->getRow('created_at');
                },
            ],
            [
                'attribute' => 'date_delivery',
                'header' => 'Дата доставки',
                'format' => 'text',
                'value' => function ($model) {
                    /**
                     * @var $model Orders
                     */
                    return $model->getRow('date_delivery');
                },
            ],
            [
                'attribute' => 'user_name',
                'header' => 'Пользователь',
                'format' => 'text',
                'value' => function ($model) {
                    /**
                     * @var $model Orders
                     */
                    return ($model->user_name) ? $model->user_name : '';
                },
            ],
            [
                'attribute' => 'user_phone',
                'header' => 'Телефон',
                'format' => 'text',
                'value' => function ($model) {
                    /**
                     * @var $model Orders
                     */
                    return ($model->user_phone) ? $model->user_phone : '';
                },
            ],
            [
                'attribute' => 'full_price',
                'header' => 'Сумма',
                'format' => 'text',
                'value' => function ($model) {
                    /**
                     * @var $model Orders
                     */
                    return ($model->full_price) ? $model->full_price : '';
                },
            ],
            [
                'attribute' => 'bonus_use',
                'header' => 'Испол-но бонусов',
                'format' => 'text',
                'value' => function ($model) {
                    /**
                     * @var $model Orders
                     */
                    return ($model->bonus_use) ? $model->bonus_use : 0;
                },
            ],
            [
                'attribute' => 'bonus_add',
                'header' => 'Получено бонусов',
                'format' => 'text',
                'value' => function ($model) {
                    /**
                     * @var $model Orders
                     */
                    return ($model->bonus_add) ? $model->bonus_add : 0;
                },
            ],
            [
                'attribute' => 'city_id',
                'header' => 'Город',
                'format' => 'text',
                'value' => function ($model) use ($city_all) {
                    /**
                     * @var $model Orders
                     */
                    return (isset($city_all[$model->city_id]) ? $city_all[$model->city_id]->name : 'Не выбран');
                },
            ],
            [
                'attribute' => 'status',
                'header' => 'Статус',
                'format' => 'text',
                'value' => function ($model) {
                    /**
                     * @var $model Orders
                     */
                    return $model->getRow('status');
                },
            ],
            [
                'attribute' => 'manager_id',
                'header' => 'Менеджер',
                'format' => 'text',
                'value' => function ($model) use ($users_all) {
                    /**
                     * @var $model Orders
                     */
                    return (isset($users_all[$model->manager_id]) ? $users_all[$model->manager_id]->username : 'Нет');
                },
            ],
        ];
        \moonland\phpexcel\Excel::export(
            [
                'fileName' => 'export_orders',
                'models' => $q->orderBy(['created_at' => SORT_DESC])->all(),
                'columns' => $columns,
//            'savePath' => Yii::getAlias('@frontend/tmp'),
//            'asAttachment' => false
            ]
        );
    }

    public function actionTest()
    {
        phpinfo();
        exit();
    }

    public function actionRollbackPay($id)
    {
        /**
         * @var $order Orders
         */
        $result = [];
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $order = Orders::findOne($id);

            // Временный код. Просто меняем статус.
            if ($order && $order->pay_status != 'success_rollback' && in_array(
                    $order->status, [6, 7]
                )) {

                $order->status = 10;
                $order->pay_status = 'success_rollback';

                if(!$order->save()){
                    $result['error'] = 'Ошибка подтверждения возврата!';
                }else{
                    $result['url'] = Url::to($this->url['back']);
                    $result['js'] = <<<JS
                    window.location = '{$result['url']}'; 
JS;
                }

            } else {
                d::pe('Данный заказ не подходит под необходимые критерии');
                $result['error'] = 'Данный заказ не подходит под необходимые критерии';
            }

            /*
             * Для кнопки "Возврат" нужно просто установить соответствующий статус,
             * без процессов оплаты/возврата оплаты.
             * По этому этот код временно не нужен.
             */
//            if ($order && $order->payment == 2 && $order->pay_status != 'success_rollback' && in_array(
//                    $order->status, [6, 7]
//                )) {
//
//                d::pe('Отмена заказа!');
//
//                $sum_pay = OrdersPay::find()->where(['order_id' => $order->id, 'status' => [0, 1]])->sum('amount');
//                $order_sum = $order->realSum();
//                $rollback_sum = floatval($sum_pay);
//                if ($order->status == 6) {//Полный возврат
//                    $real_sum = 0;
//                } else {//Частичный возврат
//                    $rollback_sum = $sum_pay - $order_sum;
//                    $real_sum = $sum_pay - $rollback_sum;
//                }
//                $rollback_url_pay = Json::encode(Url::to(['orders/send-rollback-pay', 'id' => $order->id]));
//                $result['js'] = <<<JS
//    bootbox.confirm({
//        message: 'Сумма возврата: {$rollback_sum} <br/> Сумма списания: {$real_sum}',
//        buttons: {
//            confirm: {
//                label: 'Подтвердить',
//                className: 'btn-success'
//            },
//            cancel: {
//                label: 'Закрыть',
//                className: 'btn-danger'
//            }
//        },
//        callback: function (result) {
//            if (result) {
//                $.ajax({
//                    url: {$rollback_url_pay},
//                    type: 'GET',
//                    dataType: 'JSON',
//                    success: function (data) {
//                        if (typeof data.error != 'undefined') {
//                            $.growl.error({title: 'Ошибка', message: data.error, duration: 5000});
//                        }
//                        if (typeof data.success != 'undefined') {
//                            window.location.reload();
//                        }
//                    },
//                    error: function () {
//                        $.growl.error({title: 'Ошибка', message: 'Произошла ошибка на стороне сервера!', duration: 5000});
//                    }
//                })
//
//            }
//        },
//        className: "bootbox-sm"
//    });
//JS;
//            } else {
//                d::pe('Данный заказ не подходит под необходимые критерии');
//                $result['error'] = 'Данный заказ не подходит под необходимые критерии';
//            }
        }

//        d::pe($result);

        return $result;
    }

    public function actionSendRollbackPay($id)
    {
        /**
         * @var $order Orders
         */
        $result = [];
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $order = Orders::findOne($id);
            if ($order && $order->payment == 2 && $order->pay_status != 'success_rollback' && in_array(
                    $order->status, [6, 7]
                )) {
                if ($order->status == 6) {//Полный возврат
                    $order->rollbackAllPay();
                } else {//Частичный возврат
                    $order->successPay();
                }
                // wait_surcharge
                Orders::updateAll(['pay_status' => 'success_rollback'], ['id' => $order->id]);
                $result['success'] = true;
            } else {
                $result['error'] = 'Данный заказ не подходит под необходимые критерии';
            }
        }

        return $result;
    }

    public function actionSendPay($id)
    {
        /**
         * @var $order Orders
         */
        $result = [];
        if (Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;
            $order = Orders::findOne($id);
            if ($order && $order->payment == 2 && $order->pay_status != 'wait_surcharge' && ($add_sum = $order->addSumPay())) {
                if ($url = $order->sendAddPay($add_sum)) {
                    $result['success'] = 'Запрос отправлен';
                    $result['url'] = $url;
                } else {
                    $result['error'] = 'Не удалось отправить запрос';
                }
            } else {
                $result['error'] = 'Данный заказ не подходит под необходимые критерии';
            }

            return $result;
        } else {
            if ($result) {
                foreach ($result as $key => $value) {
                    \Yii::$app->session->setFlash($key, $value);
                }
            }

            return $this->goBack();
        }
    }
}