<?php
/**
 * Created by PhpStorm.
 * Project: aitas
 * User: lxShaDoWxl
 * Date: 29.01.16
 * Time: 14:08
 */
namespace backend\controllers\main;

use backend\AdminController;
use backend\models\LSourceMessage;
use yii\data\Pagination;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Inflector;

class LangTextController extends AdminController
{
    public function init()
    {
        $this->model = new LSourceMessage();
        $controller_name = Inflector::camel2id($this->id);
        $this->url = [
            'back' => [$controller_name.'/index'],
            'control' => [$controller_name.'/control']
        ];
        $this->view->title = 'Переводы';
        $this->MenuActive($controller_name);
        $this->breadcrumb[] = [
            'url' => [$controller_name.'/index'],
            'label' => 'Переводы'
        ];
        parent::init(); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['loginAdminPanel'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'control' => ['post', 'get'],
//                    'filter' => ['post', 'get'],
                ],
            ],
        ];
    }
    public function actionIndex()
    {
        $model = LSourceMessage::find()->orderBy(['id' => SORT_DESC])->where(['category' => 'main']);
        if($search=\Yii::$app->request->get('search')){
            $model->andWhere([
                'or',
                ['like', 'default', $search],
            ]);
        }
        $pages = new Pagination(['totalCount' => $model->count()]);
        $pages->setPageSize(20);
        $data['pages'] = $pages;
        $data['items'] = $model->offset($pages->offset)
            ->limit($pages->limit)
            ->all();
        return $this->render('//main/lang_text', $data);
    }
}