<?php
namespace backend\models\main;

use backend\models\Settings;
use shadow\SSettings;
use shadow\widgets\CKEditor;
use yii\db\ActiveQuery;
use yii\helpers\FileHelper;
use yii\helpers\Html;
use yii\web\UploadedFile;

/**
 * Class TextModel
 * @package backend\models\main
 *
 * @property array $data
 */
class TextModel extends Settings
{
    public function FormParams()
    {
        $q = Settings::find();
        $groups_ids = array_keys($this->groups);
        if ($groups_ids) {
            $q->andWhere(['group' => $groups_ids]);
        }
        /** @var Settings[] $settings */
        $settings = $q->all();
        $old_settings = [];
        foreach ($settings as $item) {
            if (isset($this->data[$item->key])) {
                $params_data = $this->data[$item->key];
                $old_settings[$item->key] = $item->value;
                if (isset($params_data['lang'])) {
                    foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                        if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                            $old_settings[$item->key . '_' . $key_lang] = $item->{'value_' . $key_lang};
                        }
                    }
                }
            }
        }
        if ($old_settings) {
            $this->setOldAttributes($old_settings);
            $this->setAttributes($old_settings);
        }
        $groups = [];
        foreach ($this->data as $key => $val) {
            $group_key = (isset($val['group']) ? $val['group'] : 'main');
            $params = (isset($val['params']) ? $val['params'] : []);
            if (!isset($groups[$group_key])) {
                $groups[$group_key] = $this->groups[$group_key];
                $groups[$group_key]['fields'] = [];
            }
            $groups[$group_key]['fields'][$key] = $params;

            if (isset($val['lang'])) {
                $groups[$group_key]['fields'][$key]['field_options']['options'] = [
                    'data' => [
                        'lang' => \Yii::$app->params['defaultLanguage']
                    ]
                ];
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $groups[$group_key]['fields'][$key . '_' . $key_lang] = $params;
                        $groups[$group_key]['fields'][$key . '_' . $key_lang]['field_options']['options'] = [
                            'data' => [
                                'lang' => $key_lang
                            ],
                            'style' => 'display:none;'
                        ];
                    }
                }
            }
        }
        $result = [
            'form_action' => ['text/save'],
//            'cancel' => ['settings/control'],
            'groups' => $groups
        ];
        return $result;
    }
    protected $groups = [
        'main' => [
            'title' => 'Основные',
            'options' => [],
        ],
        'contacts' => [
            'title' => 'Контакты',
            'options' => [],
        ],
        'text_index' => [
            'title' => 'На главной',
            'options' => [],
        ],
    ];
    /**
     * @inheritdoc
     */
    public function __get($name)
    {
        if ($name == 'data') {
            return $this->getData();
        }
        return parent::__get($name); // TODO: Change the autogenerated stub
    }

    public function getData()
    {
        return [
            'header_address' => [
                'name' => 'Адрес в шапке',
                'group' => 'main',
                'params' => [],
            ],
            'footer_text' => [
                'name' => 'Текст в подвале',
                'group' => 'main',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'enterMode' => 0
                            ]
                        ]
                    ],
                ],
            ],
            'main_phone' => [
                'name' => 'Основные телефоны (разделять , )',
                'group' => 'main',
                'params' => [
                    'type' => 'textArea',
                ],
            ],
            'text_delivery_popup' => [
                'name' => 'Текст доставки',
                'group' => 'main',
                'params' => [
                    'type' => 'textArea',
                    'widget' => [
                        'class' => CKEditor::className(),
                        'config' => [
                            'editorOptions' => [
                                'enterMode' => 0
                            ]
                        ]
                    ],
                ],
            ],
            'contacts_address' => [
                'name' => 'Адрес',
                'group' => 'contacts',
                'params' => [
                    'type' => 'textArea',
                ],
            ],
            'contacts_time_work' => [
                'name' => 'Время работы',
                'group' => 'contacts',
                'params' => [
                ],
            ],
        ];
    }
    public $id = null;
    /**
     * @inheritdoc
     */
    public function formName()
    {
        return 'settings'; // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function attributes()
    {
        $result = [];
        foreach ($this->data as $key => $item) {
            $result[] = $key;
            if (isset($item['lang'])) {
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $result[] = $key . '_' . $key_lang;
                    }
                }
            }
        }
        return $result;
    }
    protected $_attribute_labels = false;
    public function attributeLabels()
    {
        $labels = [];
        if ($this->_attribute_labels === false) {
            foreach ($this->data as $key => $val) {
                if (isset($val['name'])) {
                    $name = $val['name'];
                    $labels[$key] = $name;
                    if (isset($val['lang']) && $val['lang']) {
                        foreach (\Yii::$app->params['languages'] as $language => $label) {
                            $labels[$key . '_' . $language] = $name . ' ' . $label;
                        }
                    }
                }
            }
            $this->_attribute_labels = $labels;
        } else {
            $labels = $this->_attribute_labels;
        }
        return $labels;
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        $result = [];
        $safe = [];
        foreach ($this->data as $key => $val) {
            $rule = (isset($val['rule'])) ? $val['rule'] : ([[$key], 'string']);
            $result[] = $rule;
            $safe[] = $key;
            if (isset($val['lang'])) {
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $safe[] = $key . '_' . $key_lang;
                        $rule[0] = $key . '_' . $key_lang;
                        $result[] = $rule;
                    }
                }
            }
        }
        $result[] = [$safe, 'safe'];
        return $result;
    }
    /**
     * @inheritdoc
     */
    public function save($runValidation = true, $attributeNames = null)
    {
        /**
         * @var $settings Settings
         */
        $settings = Settings::find()->indexBy('key')->all();
        $attributes = $this->data;
        $attributes_values = [];
        foreach ($attributes as $key_attribute => $attribute) {
            $value_attr = $this->getAttribute($key_attribute);
            $val = $this->saveAttribute($key_attribute, $value_attr, (isset($attribute['params']) ? $attribute['params'] : []), $settings);
            $attribute_val = [
                'group' => (isset($attribute['group'])) ? $attribute['group'] : 'main',
                'key' => $key_attribute,
                'value' => $val
            ];
            if (isset($attribute['lang'])) {
                foreach (\Yii::$app->params['languages'] as $key_lang => $lang) {
                    if ($key_lang != \Yii::$app->params['defaultLanguage']) {
                        $name = $key_attribute . '_' . $key_lang;
                        $value_attr = $this->getAttribute($name);
                        $val = $this->saveAttribute($name, $value_attr, (isset($attribute['params']) ? $attribute['params'] : []), $settings, $key_lang);
                        $attribute_val['value_' . $key_lang] = $val;
                    }
                }
            }
            $attributes_values[$key_attribute] = $attribute_val;
        }
        /**
         * @var $record Settings
         */
        foreach ($attributes_values as $key => $attributes_value) {
            if (isset($settings[$key])) {
                $record = $settings[$key];
                $update = false;
                foreach ($attributes_value as $key_name => $value) {
                    if ($record->{$key_name} != $value || $record->{$key_name} == null) {
                        $record->{$key_name} = $value;
                        $update = true;
                    }
                }
                if ($update) {
                    $record->save(false);
                }
            } else {
                $record = new Settings();
                $record->setAttributes($attributes_value);
                $record->save(false);
            }
        }
        \yii\caching\TagDependency::invalidate(\Yii::$app->frontend_cache, SSettings::CACHE_TAG_KEY);
        return true;
    }
    public function saveAttribute($attribute, $value, $params = [], $settings = [], $key_lang = false)
    {
        $type = (isset($params['type'])) ? $params['type'] : 'text';
        switch ($type) {
            case 'img':
            case 'file':
                $file = UploadedFile::getInstance($this, $attribute);
                if ($file) {
                    $path = \Yii::getAlias("@web_frontend/uploads/settings/{$attribute}.{$file->getExtension()}");
                    if (!is_dir(pathinfo($path, PATHINFO_DIRNAME))) {
                        FileHelper::createDirectory(pathinfo($path, PATHINFO_DIRNAME), 0775, true);
                    }
                    $file->saveAs($path);
                    $value = "/uploads/settings/{$attribute}.{$file->getExtension()}";
                } else {
                    if ($value == 'deleted') {
                        $value = '';
                        $path_file = \Yii::getAlias('@web_frontend') . $value;
                        if (is_file($path_file)) {
                            @unlink($path_file);
                        }
                    } elseif (isset($settings[$attribute])) {
                        $value = $settings[$attribute]->value;
                    } elseif ($key_lang && isset($settings[str_replace('_' . $key_lang, '', $attribute)])) {
                        $value = $settings[str_replace('_' . $key_lang, '', $attribute)]->{'value_'.$key_lang};
                    }
                }
        }
        return $value;
    }
    public function behaviors()
    {
        return [];
    }
    public static function find()
    {
        return \Yii::createObject(ActiveQuery::className(), [get_called_class()]);
    }
    public function addButtons()
    {
        if (count(\Yii::$app->params['languages']) > 1) {
            $langs = '';
            $default_lang = \Yii::$app->params['defaultLanguage'];
            foreach (\Yii::$app->params['languages'] as $key => $value) {
                $class = null;
                if ($key == $default_lang) {
                    $class .= 'active';
                }
                $langs .= Html::tag(
                    'li',
                    Html::a(
                        Html::tag('span', strtoupper($key)),
                        '#',
                        [
                            'class' => 'change_lang',
                            'data' => [
                                'lang' => $key
                            ]
                        ]
                    ),
                    [
                        'class' => $class,
                    ]
                );
            }
            $view = \Yii::$app->controller->view;
            $view->registerJs(<<<JS
$('.change_lang', '#pageEdit').on('click', function (e) {
    e.preventDefault();
    $(this).closest('ul').children('li').removeClass('active');
    $(this).closest('li').addClass('active');
    change_lang($(this).data('lang'));
});
function change_lang(lang) {
    $('.form-group', '#pageEdit').each(function () {
        if (typeof $(this).data('lang') != 'undefined') {
            if ($(this).data('lang') == lang) {
                $(this).show();
            } else {
                $(this).hide();
            }
        }
    });
}
JS
            );
            return '<div class="pull-right-sm"><ul class="nav nav-tabs">' . $langs . '</ul></div>';
        } else {
            return '';
        }
    }
}